/* ---------------------------------------------------------------
   STORY: Abby's Brave Day  (WRS Substep 5.4AB)
   A firefighter saves homes from wildfire — and one unexpected family of cats — multisyllabic words with the welded -ive suffix.
   Auto-split from the original single-file build — safe to hand-edit.
   To add a NEW story, copy this whole file, rename the three consts
   and the STORY_PACKS key/id, then add a <script src="stories/yourfile.js">
   line in index.html (order in that list = order in the case picker).
   Set type to 'authentic' for real-world (non-controlled) passages — this only
   changes the badge shown on the picker card, not how rounds are built.
--------------------------------------------------------------- */
const KEY_TERMS_ABBY_BRAVE = ['mother(s)','father(s)','son(s)','daughter(s)','ton','brother(s)','sister(s)'];

const STORY_PARAGRAPHS_ABBY_BRAVE = [
  `The hillside wildfires are now developing into a big risk for the homeowners of the local district. Mothers, fathers, sons, and daughters have all been told to exit their homes and find a safe place away from the destructive event.`,
  `But not Abby. In the firetruck, Abby makes her way toward the unprotected homes close to the hillside. Abby is part of a unit of twenty-five firemen and firewomen, and they are never off-duty. It is their job to ensure that all the occupants relocate to a secure spot. It is sad to have to dislocate all these people, but there is too much at stake not to move them.`,
  `Abby and her unit will check each and every home. They are intent on checking all twenty-nine homes on the block. They must readjust their equipment when the hot flames shift with the winds. It is work with a ton of risk, but Abby has always been a brave person.`,
  `As the flames extend past the hills, the fire unit progresses to one home after another. At the sixth house, Abby walks around and checks the back of the home. All of a sudden, she detects a soft cry from under the deck. She looks and finds out that the cry is coming from a cat. In fact, Abby spots not just one cat, but a mother cat and five kittens!`,
  `The protective mother cat has been calling for help, but she has the good sense to hide and care for her kittens. The mother cat has a tag around her neck, and Abby finds that her name is Ladybug. Abby had not expected to save a nonhuman on this day, but she knows that all life is important.`,
  `Abby inches her way under the deck, attentive to the fact that Ladybug may not respond well to her help. One by one, Abby puts the mother cat and all the kittens into her bag and sprints off to the firetruck. She has to readjust the strap on her bag more than once as she runs.`,
  `Abby makes it to the firetruck. She deposits the bag into the back of the truck, unzips it, and lets the cats out. She tells Ladybug that she has been the best mother to protect these small kittens. Abby gives all the cats some water, then tells them, "Don't be unhappy. We will reconnect you with your owners, but for now, you will be safe in here." Away from the wildfire, Ladybug and all the kitten brothers and sisters can relax now.`,
];

const ROUNDS_ABBY_BRAVE = [
  { id:'sequence', tab:'Timeline', title:"Case File 1 — Timeline Reconstruction", icon:'🗺️',
    intro:"Drag the evidence into the correct order to rebuild Abby's brave day.",
    type:'sequence', points:5,
    sets:[
      { label:'Checking the homes — put these in order', events:[
          "Homeowners are told to exit their homes because of the wildfire.",
          "Abby drives the firetruck toward the unprotected homes.",
          "Abby's unit checks each of the twenty-nine homes on the block.",
          "At the sixth house, Abby hears a soft cry from under the deck.",
      ]},
      { label:'Saving the cats — put these in order', events:[
          "Abby discovers a mother cat and five kittens.",
          "Abby learns the mother cat's name is Ladybug.",
          "Abby puts the cats into her bag and sprints to the firetruck.",
          "Abby lets the cats out of the bag and gives them water.",
      ]},
    ]},
  { id:'inference', tab:'Inference', title:"Case File 2 — Detective Inference", icon:'🧠',
    intro:"The best clues aren't always written in the text. Read between the lines to solve these.",
    type:'mc', points:12,
    questions:[
      {context:`"But not Abby. In the firetruck, Abby makes her way toward the unprotected homes close to the hillside."`, prompt:'What does "but not Abby" suggest, right after homeowners were told to leave?', 
        options:['Abby is also leaving the area','Abby is heading toward danger instead of away from it, because it\'s her job','Abby doesn\'t know about the wildfire','Abby is confused about where to go'], answer:1,
        explain:'Everyone else is told to exit, but Abby drives toward the unprotected homes — the contrast shows she\'s heading into danger rather than away from it, as part of her job.'},
      {context:`"It is sad to have to dislocate all these people, but there is too much at stake not to move them."`, prompt:'What does this tell you about Abby\'s feelings about her job?', 
        options:['She enjoys forcing people from their homes','She feels conflicted — sad about the disruption, but knows it\'s necessary','She doesn\'t care about the homeowners','She thinks the evacuation is unnecessary'], answer:1,
        explain:'"Sad" shows genuine feeling for the people affected, while "too much at stake" shows she still believes the action is necessary — both feelings exist together.'},
      {context:`"It is work with a ton of risk, but Abby has always been a brave person."`, prompt:'What does this line tell you about why Abby can do this job?', 
        options:['She doesn\'t understand the risk involved','Her natural bravery helps her handle a genuinely risky job','She has no other job options','She thinks the job has no risk at all'], answer:1,
        explain:'The sentence directly connects the "ton of risk" with Abby "always" being brave — her bravery is presented as the reason she can do this dangerous work.'},
      {context:`"All of a sudden, she detects a soft cry from under the deck."`, prompt:'What does "all of a sudden" suggest about this moment?', 
        options:['Abby was expecting to hear the cry','The cry was an unexpected discovery during her routine check','Abby ignored the sound','The cry came from a person'], answer:1,
        explain:'"All of a sudden" signals something unplanned and surprising — Abby wasn\'t searching for the cats, she stumbled onto the cry unexpectedly.'},
      {context:`"Abby had not expected to save a nonhuman on this day, but she knows that all life is important."`, prompt:'What does this reveal about Abby\'s values?', 
        options:['She only cares about saving human lives','She believes all living creatures deserve to be saved, not just people','She regrets helping the cats','She thinks animals are less important than her job'], answer:1,
        explain:'"All life is important" is a direct statement of Abby\'s belief — even though her job is about human homes, she extends that same care to the cats.'},
      {context:`"Abby inches her way under the deck, attentive to the fact that Ladybug may not respond well to her help."`, prompt:'What does this tell you about how Abby approaches the mother cat?', 
        options:['Carelessly and quickly','Carefully and cautiously, aware the cat might be defensive','Angrily, wanting to scare the cat away','Without any thought for the cat\'s reaction'], answer:1,
        explain:'"Inches her way" and being "attentive" to a possible bad reaction both show Abby moving slowly and carefully, respecting that a protective mother cat could react defensively.'},
      {context:`"She has to readjust the strap on her bag more than once as she runs."`, prompt:'What can you infer about how difficult this part of the rescue is?', 
        options:['It was effortless for Abby','It required real physical effort and persistence','Abby gave up before reaching the truck','The bag was empty and light'], answer:1,
        explain:'Needing to "readjust" a strap "more than once" while running with a bag full of cats shows this was physically demanding, not effortless.'},
      {context:`"She tells Ladybug that she has been the best mother to protect these small kittens."`, prompt:'Why might Abby say this to Ladybug?', 
        options:['To criticize the cat\'s parenting','To acknowledge and validate the cat\'s protective instincts','Because she is angry at the cat','Because it is required paperwork'], answer:1,
        explain:'Complimenting Ladybug as "the best mother" recognizes the protective behavior the cat showed earlier — hiding and caring for her kittens despite the danger.'},
      {context:'Think about the whole story.', prompt:'What is one theme this story explores?', 
        options:['Bravery and compassion can extend beyond a person\'s official duties','Firefighters only care about buildings, not living things','Rescuing animals is a waste of time during emergencies','Wildfires are not very dangerous'], answer:0,
        explain:'Abby\'s official job is relocating homeowners, but she goes out of her way to save a cat family too — showing bravery and compassion beyond just her assigned duty.'},
    ]},
  { id:'vocab', tab:'Vocab', title:"Case File 3 — Vocabulary Clues", icon:'🔍',
    intro:"Every good detective reads for clues hidden in context. Figure out what each word means the way it's used in the story.",
    type:'mc', points:10,
    questions:[
      {context:`"The hillside wildfires are now developing into a big risk for the homeowners of the local district."`, prompt:'What does district mean here?', 
        options:['A single house','A defined area or region','A type of fire truck','A weather pattern'], answer:1,
        explain:'A district is a defined area or region — here, the local area affected by the wildfire.'},
      {context:`"Find a safe place away from the destructive event."`, prompt:'What does destructive mean here?', 
        options:['Helpful and constructive','Causing damage or ruin','Quiet and calm','Small and harmless'], answer:1,
        explain:'Destructive describes something that causes damage — fitting a dangerous wildfire event.'},
      {context:`"Abby makes her way toward the unprotected homes."`, prompt:'What does unprotected mean here?', 
        options:['Fully guarded and safe','Not guarded or shielded from danger','Recently built','Very expensive'], answer:1,
        explain:'Unprotected describes homes without safety or shielding — exactly the homes at risk from the wildfire that Abby is heading toward.'},
      {context:`"It is their job to ensure that all the occupants relocate to a secure spot."`, prompt:'What does occupants mean here?', 
        options:['The firefighters','The people living in the homes','The wildfire itself','The equipment used'], answer:1,
        explain:'Occupants refers to the people living in or using a space — here, the residents who need to be moved to safety.'},
      {context:`"It is sad to have to dislocate all these people."`, prompt:'What does dislocate mean here?', 
        options:['To injure someone','To force people to move from their location','To celebrate with people','To ignore people'], answer:1,
        explain:'Dislocate here means to force or require people to move away from where they normally are — their homes.'},
      {context:`"They must readjust their equipment when the hot flames shift with the winds."`, prompt:'What does readjust mean here?', 
        options:['To throw away','To change or fix again as conditions change','To buy new equipment','To ignore the change'], answer:1,
        explain:'Readjust means to adjust again — the firefighters have to keep changing their approach as the fire\'s direction shifts.'},
      {context:`"They are intent on checking all twenty-nine homes on the block."`, prompt:'What does intent mean here?', 
        options:['Uninterested','Firmly determined and focused on a goal','Confused about the plan','Afraid to continue'], answer:1,
        explain:'Being "intent on" something means being firmly determined to do it — the unit is focused on checking every single home.'},
      {context:`"The protective mother cat has been calling for help."`, prompt:'What does protective mean here?', 
        options:['Careless about danger','Wanting to guard and keep something safe','Angry and aggressive','Confused and lost'], answer:1,
        explain:'Protective describes wanting to guard and keep something safe — here, the mother cat looking out for her kittens.'},
      {context:`"Abby inches her way under the deck, attentive to the fact that Ladybug may not respond well."`, prompt:'What does attentive mean here?', 
        options:['Careless and distracted','Paying close, careful attention','Loud and forceful','Confused and unsure'], answer:1,
        explain:'Attentive means paying close attention — Abby is being careful and mindful of how the cat might react.'},
      {context:`"We will reconnect you with your owners."`, prompt:'What does reconnect mean here?', 
        options:['To separate permanently','To bring back together again','To ignore completely','To trap somewhere new'], answer:1,
        explain:'Reconnect means to bring back together — Abby is promising to reunite the cats with their owners.'},
    ]},
  { id:'spelling', tab:'Spelling', title:"Case File 4 — Spelling Forensics", icon:'✏️',
    intro:"A detective's notes have to be exact. Listen to each word and spell it correctly to file it as evidence.",
    type:'spell', points:15,
    questions:[
      {word:'district', sentence:'The wildfire risks the local district.'},
      {word:'destructive', sentence:'People flee the destructive event.'},
      {word:'relocate', sentence:'Occupants must relocate to safety.'},
      {word:'dislocate', sentence:'It is sad to dislocate these people.'},
      {word:'readjust', sentence:'They readjust their equipment.'},
      {word:'equipment', sentence:'The flames shift, so they readjust their equipment.'},
      {word:'attentive', sentence:'Abby is attentive to the cat\'s reaction.'},
      {word:'protective', sentence:'The protective mother cat hides her kittens.'},
      {word:'reconnect', sentence:'Abby will reconnect the cats with their owners.'},
      {word:'occupants', sentence:'All the occupants must relocate.'},
    ]},
  { id:'structure', tab:'Structure', title:"Case File 5 — Structure Analysis", icon:'🧩',
    intro:"This story leans on the welded suffix -ive. Mark the sound chunks to crack the code.",
    type:'mc', points:10,
    questions:[
      {context:'destructive', prompt:'Which letters form the welded suffix?', options:['de','struc','ive','ct'], answer:2,
        explain:'"Ive" is a welded suffix — the i, v, and e glue together into one chunk that\'s always read as a unit.'},
      {context:'attentive', prompt:'Which letters form the welded suffix?', options:['at','ten','ive','nt'], answer:2,
        explain:'"Ive" is welded the same way here as in destructive and protective — always one chunk, never split apart.'},
      {context:'protective', prompt:'Which letters form the welded suffix?', options:['pro','tec','ive','ct'], answer:2,
        explain:'Like destructive and attentive, protective ends in the welded chunk "ive."'},
      {context:'district', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'District breaks into two syllable chunks: dis-trict, both closed syllables.'},
      {context:'relocate', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:2,
        explain:'Relocate breaks into three syllable chunks: re-lo-cate, ending in a VCE syllable that gives the a its long sound.'},
      {context:'dislocate', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:2,
        explain:'Dislocate breaks into three syllable chunks: dis-lo-cate, ending in a VCE syllable, just like relocate.'},
      {context:'readjust', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:2,
        explain:'Readjust breaks into three syllable chunks: re-ad-just.'},
      {context:'equipment', prompt:'Which letters form the beginning digraph-like blend?', options:['qu','ip','me','nt'], answer:0,
        explain:'Qu is treated as a single consonant tile in this system — it always appears together and makes one combined sound.'},
      {context:'reconnect', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:2,
        explain:'Reconnect breaks into three syllable chunks: re-con-nect.'},
      {context:'occupants', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:2,
        explain:'Occupants breaks into three syllable chunks: oc-cu-pants.'},
    ]},
];

STORY_PACKS['abby_brave_day'] = {
  id: 'abby_brave_day',
  title: "Abby's Brave Day",
  substep: '5.4AB',
  blurb: 'A firefighter saves homes from wildfire — and one unexpected family of cats — multisyllabic words with the welded -ive suffix.',
  type: 'controlled', // 'controlled' (WRS-decodable) or 'authentic' (real-world text)
  keyTerms: KEY_TERMS_ABBY_BRAVE,
  paragraphs: STORY_PARAGRAPHS_ABBY_BRAVE,
  rounds: ROUNDS_ABBY_BRAVE,
};
STORY_ORDER.push('abby_brave_day');
