/* ---------------------------------------------------------------
   STORY: Anna on Skates  (WRS Substep 5.5B)
   A figure skater's path to the World Finals gold medal — multisyllabic words with the welded -ive suffix and VCE syllables.
   Auto-split from the original single-file build — safe to hand-edit.
   To add a NEW story, copy this whole file, rename the three consts
   and the STORY_PACKS key/id, then add a <script src="stories/yourfile.js">
   line in index.html (order in that list = order in the case picker).
   Set type to 'authentic' for real-world (non-controlled) passages — this only
   changes the badge shown on the picker card, not how rounds are built.
--------------------------------------------------------------- */
const KEY_TERMS_ANNA_SKATES = ['since','almost','family','early','sport','see','team','soon'];

const STORY_PARAGRAPHS_ANNA_SKATES = [
  `Anna has been on skates since she was almost four years old. She has spent most of her days at the rink. Anna and her family had to dedicate themselves to this sport early on in her life. She now skates at the top competitive level and is in first-rate shape. Her objective is to skate in the World Finals.`,
  `Anna is both athletic and talented, and she has an intensive work ethic. She also has to be optimistic and confident about her ability to win. Anna has a right to be confident because her act has all the most difficult elements. She captivates the people in the stands, and it is a thrill to see her skate.`,
  `In the fall, Anna makes the World Finals team, so now it is more important than ever for her to prepare. The prospect of a gold medal inspires her. So much will depend on the last event - the long program. A drastic mistake or even a small slip will impact the result.`,
  `At the finals, Anna has one last skate to try to win the gold. She goes into the event with a positive attitude. Her music has a fast tempo, and the fans clap as she glides across the rink. Her landing leg is solid when she executes her axel and flip jumps. She is elegant! The fans adore her as she finishes her program with a pivot of her skates and a divine camel spin.`,
  `Anna has done her best and soon the scores come in. She has won the gold medal! Anna shakes hands with her opponents from Finland and China. She compliments them on their fantastic programs.`,
  `Then, Anna almost begins to cry as she gives a big wave to the jubilant fans in the stands. When the press comes by, Anna thanks her family and friends. She hopes to always recall this uncommon moment in her life.`,
];

const ROUNDS_ANNA_SKATES = [
  { id:'sequence', tab:'Timeline', title:"Case File 1 — Timeline Reconstruction", icon:'🗺️',
    intro:"Drag the evidence into the correct order to rebuild Anna's road to the gold medal.",
    type:'sequence', points:5,
    sets:[
      { label:'Before the finals — put these in order', events:[
          "Anna dedicates herself to skating from a young age.",
          "Anna builds an intensive work ethic and confidence.",
          "Anna makes the World Finals team in the fall.",
          "Anna knows a small slip could impact the whole result.",
      ]},
      { label:'At the finals — put these in order', events:[
          "Anna skates her program with a positive attitude.",
          "Anna finishes with a pivot and a camel spin.",
          "The scores come in and Anna wins the gold medal.",
          "Anna waves to the jubilant fans and thanks her family.",
      ]},
    ]},
  { id:'inference', tab:'Inference', title:"Case File 2 — Detective Inference", icon:'🧠',
    intro:"The best clues aren't always written in the text. Read between the lines to solve these.",
    type:'mc', points:12,
    questions:[
      {context:`"Anna and her family had to dedicate themselves to this sport early on in her life."`, prompt:'What does this tell you about the level of commitment Anna\'s success required?', 
        options:['Anna became skilled with little effort','Reaching a high level required long-term dedication from Anna and her family','Her family was uninvolved in her skating','She started skating as an adult'], answer:1,
        explain:'"Dedicate themselves" and "early on in her life" both point to a long-term, family-wide commitment, not a quick or easy path.'},
      {context:`"She also has to be optimistic and confident about her ability to win."`, prompt:'What does this suggest about the mental side of competitive skating?', 
        options:['Physical skill alone is enough to win','Mindset and confidence matter alongside physical skill','Optimism has no effect on performance','Confidence can hurt a skater\'s chances'], answer:1,
        explain:'The story pairs "optimistic and confident" right alongside her athletic talent — suggesting mental attitude is just as important as physical ability.'},
      {context:`"The prospect of a gold medal inspires her."`, prompt:'What does this tell you about Anna\'s motivation?', 
        options:['She is discouraged by the difficulty ahead','The possibility of winning gold drives and motivates her effort','She doesn\'t care about winning','She is motivated only by her family'], answer:1,
        explain:'"Inspires her" shows the gold medal possibility is a positive motivating force behind her preparation.'},
      {context:`"A drastic mistake or even a small slip will impact the result."`, prompt:'What does this line reveal about the pressure of the long program?', 
        options:['Mistakes don\'t matter in this event','Even a minor error could significantly affect her final outcome','The event has no real stakes','Anna is guaranteed to win regardless'], answer:1,
        explain:'Saying "even a small slip will impact the result" shows how little room for error there is — high stakes riding on near-perfect execution.'},
      {context:`"The fans adore her as she finishes her program with a pivot of her skates and a divine camel spin."`, prompt:'What does "adore" tell you about the crowd\'s reaction to Anna\'s performance?', 
        options:['They are bored and unimpressed','They deeply love and admire her performance','They are confused by her routine','They want her to stop'], answer:1,
        explain:'"Adore" is a strong word for deep admiration — showing the crowd genuinely loves watching Anna\'s performance.'},
      {context:`"Anna shakes hands with her opponents from Finland and China. She compliments them on their fantastic programs."`, prompt:'What does this moment reveal about Anna\'s character, even after winning?', 
        options:['She is arrogant about her win','She shows good sportsmanship by respecting her competitors','She ignores the other skaters','She argues with the judges'], answer:1,
        explain:'Shaking hands and complimenting her opponents right after winning shows gracious sportsmanship, not arrogance.'},
      {context:`"Then, Anna almost begins to cry as she gives a big wave to the jubilant fans in the stands."`, prompt:'What does "almost begins to cry" suggest about the emotional weight of this moment?', 
        options:['Anna is sad about the outcome','The moment is emotionally overwhelming, in a positive way','Anna is embarrassed','Anna is angry at the fans'], answer:1,
        explain:'Coming right after winning the gold medal, nearly crying while waving to adoring fans reflects overwhelming, positive emotion — not sadness.'},
      {context:`"She hopes to always recall this uncommon moment in her life."`, prompt:'What does "uncommon" suggest about how Anna views this achievement?', 
        options:['She sees it as an everyday occurrence','She recognizes this as a rare, special moment worth remembering forever','She thinks the moment was unimportant','She expects to win gold medals often'], answer:1,
        explain:'Calling the moment "uncommon" and wanting to "always recall" it shows Anna sees this as a rare, significant achievement in her life.'},
      {context:'Think about the whole story.', prompt:'What is one theme this story explores?', 
        options:['Years of dedication and mental toughness can lead to a triumphant, unforgettable moment','Winning is only about physical talent','Sportsmanship doesn\'t matter after winning','Competitive sports bring only stress, never joy'], answer:0,
        explain:'The story tracks Anna\'s long dedication, mental preparation, the risk of the final event, and then the emotional payoff of winning — that arc supports a theme about dedication leading to a triumphant outcome.'},
    ]},
  { id:'vocab', tab:'Vocab', title:"Case File 3 — Vocabulary Clues", icon:'🔍',
    intro:"Every good detective reads for clues hidden in context. Figure out what each word means the way it's used in the story.",
    type:'mc', points:10,
    questions:[
      {context:`"Anna and her family had to dedicate themselves to this sport early on in her life."`, prompt:'What does dedicate mean here?', 
        options:['To ignore something','To devote serious time and effort to something','To quit something','To criticize something'], answer:1,
        explain:'Dedicate means to devote serious time and effort — here, the whole family committing to Anna\'s sport.'},
      {context:`"She has an intensive work ethic."`, prompt:'What does intensive mean here?', 
        options:['Light and occasional','Extremely thorough and concentrated','Careless','Slow and relaxed'], answer:1,
        explain:'Intensive describes something extremely thorough and concentrated — a strong, focused work ethic.'},
      {context:`"She also has to be optimistic and confident about her ability to win."`, prompt:'What does optimistic mean here?', 
        options:['Expecting the worst outcome','Hopeful and expecting good outcomes','Feeling nervous and unsure','Feeling indifferent'], answer:1,
        explain:'Optimistic means expecting good outcomes — a hopeful mindset that pairs with confidence about winning.'},
      {context:`"She captivates the people in the stands."`, prompt:'What does captivates mean here?', 
        options:['Bores completely','Holds someone\'s attention and fascination','Confuses','Frightens'], answer:1,
        explain:'Captivates means to hold someone\'s attention and fascination — the crowd is fully engaged watching her skate.'},
      {context:`"A drastic mistake or even a small slip will impact the result."`, prompt:'What does drastic mean here?', 
        options:['Minor and unnoticeable','Severe and extreme','Common and expected','Positive and helpful'], answer:1,
        explain:'Drastic describes something severe or extreme — contrasted here with "even a small slip," showing a range from big to tiny errors.'},
      {context:`"She is elegant!"`, prompt:'What does elegant mean here?', 
        options:['Clumsy and awkward','Graceful and refined','Loud and forceful','Slow and hesitant'], answer:1,
        explain:'Elegant describes graceful, refined movement — a compliment to Anna\'s skating style.'},
      {context:`"Anna compliments them on their fantastic programs."`, prompt:'What does compliments mean here?', 
        options:['Criticizes something','Says something nice or praises something','Ignores something','Argues about something'], answer:1,
        explain:'Compliments means to say something nice or praise someone — here, Anna praising her opponents\' performances.'},
      {context:`"Anna almost begins to cry as she gives a big wave to the jubilant fans."`, prompt:'What does jubilant mean here?', 
        options:['Angry and upset','Joyful and celebratory','Bored and tired','Confused'], answer:1,
        explain:'Jubilant describes joyful, celebratory emotion — fitting fans cheering for a gold medal win.'},
      {context:`"She hopes to always recall this uncommon moment in her life."`, prompt:'What does recall mean here?', 
        options:['To forget something','To remember something','To ignore something','To repeat an action immediately'], answer:1,
        explain:'Recall means to remember — Anna wants to keep this special moment in her memory forever.'},
      {context:`"She hopes to always recall this uncommon moment in her life."`, prompt:'What does uncommon mean here?', 
        options:['Ordinary and typical','Rare and unusual','Boring','Expected'], answer:1,
        explain:'Uncommon means rare or unusual — Anna recognizes this achievement as something special, not an everyday occurrence.'},
    ]},
  { id:'spelling', tab:'Spelling', title:"Case File 4 — Spelling Forensics", icon:'✏️',
    intro:"A detective's notes have to be exact. Listen to each word and spell it correctly to file it as evidence.",
    type:'spell', points:15,
    questions:[
      {word:'athletic', sentence:'Anna is both athletic and talented.'},
      {word:'talented', sentence:'Anna is athletic and talented.'},
      {word:'intensive', sentence:'She has an intensive work ethic.'},
      {word:'optimistic', sentence:'She has to be optimistic about winning.'},
      {word:'confident', sentence:'Anna is confident in her ability.'},
      {word:'captivates', sentence:'She captivates the people in the stands.'},
      {word:'drastic', sentence:'A drastic mistake could impact the result.'},
      {word:'elegant', sentence:'Anna is elegant on the ice.'},
      {word:'jubilant', sentence:'The jubilant fans cheer for Anna.'},
      {word:'uncommon', sentence:'This is an uncommon moment for Anna.'},
    ]},
  { id:'structure', tab:'Structure', title:"Case File 5 — Structure Analysis", icon:'🧩',
    intro:"This story leans on the welded suffix -ive and multisyllabic words. Mark the sound chunks to crack the code.",
    type:'mc', points:10,
    questions:[
      {context:'intensive', prompt:'Which letters form the welded suffix?', options:['in','ten','ive','ns'], answer:2,
        explain:'"Ive" is a welded suffix — the i, v, and e glue together into one chunk that\'s always read as a unit.'},
      {context:'athletic', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:2,
        explain:'Athletic breaks into three syllable chunks: ath-let-ic.'},
      {context:'talented', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:2,
        explain:'Talented breaks into three syllable chunks: tal-ent-ed.'},
      {context:'optimistic', prompt:'How many syllables does this word have?', options:['2','3','4','5'], answer:2,
        explain:'Optimistic breaks into four syllable chunks: op-ti-mis-tic.'},
      {context:'confident', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:2,
        explain:'Confident breaks into three syllable chunks: con-fi-dent.'},
      {context:'captivates', prompt:'What syllable type is the last syllable, "vates"?', options:['Open syllable','VCE (vowel-consonant-e)','Closed syllable','Welded'], answer:1,
        explain:'"Vates" has a vowel, then a consonant, then a silent e — that pattern is a VCE syllable, giving the a its long sound.'},
      {context:'drastic', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Drastic breaks into two syllable chunks: dras-tic, both closed syllables.'},
      {context:'elegant', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:2,
        explain:'Elegant breaks into three syllable chunks: el-e-gant.'},
      {context:'jubilant', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:2,
        explain:'Jubilant breaks into three syllable chunks: ju-bi-lant.'},
      {context:'uncommon', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:2,
        explain:'Uncommon breaks into three syllable chunks: un-com-mon.'},
    ]},
];

STORY_PACKS['anna_skates'] = {
  id: 'anna_skates',
  title: "Anna on Skates",
  substep: '5.5B',
  blurb: "A figure skater's path to the World Finals gold medal — multisyllabic words with the welded -ive suffix and VCE syllables.",
  type: 'controlled', // 'controlled' (WRS-decodable) or 'authentic' (real-world text)
  keyTerms: KEY_TERMS_ANNA_SKATES,
  paragraphs: STORY_PARAGRAPHS_ANNA_SKATES,
  rounds: ROUNDS_ANNA_SKATES,
};
STORY_ORDER.push('anna_skates');
