/* ---------------------------------------------------------------
   STORY: Brody's Job at the Golf Club  (WRS Substep 5.3B)
   A caddy sizes up his two regular golfers — open syllables, closed syllables, and y as a vowel.
   Auto-split from the original single-file build — safe to hand-edit.
   To add a NEW story, copy this whole file, rename the three consts
   and the STORY_PACKS key/id, then add a <script src="stories/yourfile.js">
   line in index.html (order in that list = order in the case picker).
   Set type to 'authentic' for real-world (non-controlled) passages — this only
   changes the badge shown on the picker card, not how rounds are built.
--------------------------------------------------------------- */
const KEY_TERMS_BRODY_GOLF = ['beautiful','women','pretty','don\'t','person','odd','putts'];

const STORY_PARAGRAPHS_BRODY_GOLF = [
  `Brody just got a job as a caddy at a beautiful golf club. Brody likes the job and is happy there most of the time. A lot of lucky men and women belong to the golf club, and most of them are kind and tip Brody very well.`,
  `Brody is often the caddy for Mr. Shelby. Mr. Shelby has plenty of nifty clothes that Brody thinks must cost a pretty penny. Brody also thinks that Mr. Shelby is a silly man. He makes odd comments that don't make much sense, but his chitchat makes things kind of fun.`,
  `Mr. Shelby also has a best crony. His name is Mr. Henry, and both men say that golf is their top hobby. They are always at the club swinging at balls until sunset.`,
  `Mr. Shelby is pretty shoddy at the game, but Mr. Henry is a person who is quite talented at golf. He makes some tricky putts, and Brody admires his skills.`,
  `After a long day, Brody goes up to the loft in the golf shack. It is a bit buggy and musty, but he does not mind. It is a good time to rest, relax, and just be lazy. Being a caddy for two men like Mr. Shelby and Mr. Henry is great, but it tires Brody out!`,
];

const ROUNDS_BRODY_GOLF = [
  { id:'sequence', tab:'Timeline', title:"Case File 1 — Timeline Reconstruction", icon:'🗺️',
    intro:"Drag the evidence into the correct order to rebuild Brody's day at the club.",
    type:'sequence', points:5,
    sets:[
      { label:'On the course — put these in order', events:[
          "Brody caddies for Mr. Shelby, who makes odd comments.",
          "Mr. Shelby and his crony, Mr. Henry, swing at balls together.",
          "Mr. Henry makes some tricky putts.",
          "Brody admires Mr. Henry's talent at golf.",
      ]},
      { label:'End of the day — put these in order', events:[
          "The two men play until sunset.",
          "Brody goes up to the loft in the golf shack.",
          "Brody notices the loft is buggy and musty.",
          "Brody rests, relaxes, and feels tired out.",
      ]},
    ]},
  { id:'inference', tab:'Inference', title:"Case File 2 — Detective Inference", icon:'🧠',
    intro:"The best clues aren't always written in the text. Read between the lines to solve these.",
    type:'mc', points:12,
    questions:[
      {context:`"Most of them are kind and tip Brody very well."`, prompt:'What does this tell you about how Brody feels about his job overall?', 
        options:['He probably dislikes the job','He likely enjoys the job, since the members are kind and generous','He is planning to quit soon','He is indifferent about the members'], answer:1,
        explain:'Kind members who tip well are a good sign for a job — paired with the earlier line that Brody "likes the job," this supports him enjoying his work.'},
      {context:`"Mr. Shelby has plenty of nifty clothes that Brody thinks must cost a pretty penny."`, prompt:'What can you infer about Mr. Shelby from this line?', 
        options:['He is likely wealthy','He is likely very poor','He dislikes nice clothes','He borrows his clothes'], answer:0,
        explain:'Owning "plenty" of clothes that "cost a pretty penny" (meaning expensive) suggests Mr. Shelby has money to spend.'},
      {context:`"He makes odd comments that don't make much sense, but his chitchat makes things kind of fun."`, prompt:'What does this tell you about Brody\'s overall opinion of Mr. Shelby?', 
        options:['Brody finds him purely annoying','Brody finds him a bit odd but still enjoyable to be around','Brody wants a different golfer to caddy for','Brody thinks Mr. Shelby is boring'], answer:1,
        explain:'The word "but" signals a contrast — even though the comments are odd, Brody still finds the chitchat fun, showing a mixed but overall positive opinion.'},
      {context:`"They are always at the club swinging at balls until sunset."`, prompt:'What does "always" and "until sunset" suggest about how much these two men golf?', 
        options:['They rarely play golf','They are extremely dedicated to golf, playing long hours regularly','They only play once a year','They dislike golf but play anyway'], answer:1,
        explain:'"Always" describes a regular habit, and playing "until sunset" shows long hours — together they show real dedication to the sport.'},
      {context:`"Mr. Shelby is pretty shoddy at the game, but Mr. Henry is a person who is quite talented at golf."`, prompt:'What is this sentence comparing?', 
        options:['Two different sports','The skill levels of the two golfers','Their choice of clothing','Their friendship'], answer:1,
        explain:'The word "but" contrasts "shoddy" (poor skill) with "quite talented" — directly comparing how good each man is at golf.'},
      {context:`"He makes some tricky putts, and Brody admires his skills."`, prompt:'What does "admires" tell you about Brody\'s feelings toward Mr. Henry\'s golf ability?', 
        options:['Brody is jealous of him','Brody respects and is impressed by his skill','Brody thinks Mr. Henry is showing off','Brody wants to stop caddying for him'], answer:1,
        explain:'To admire something is to respect and be impressed by it — Brody looks up to Mr. Henry\'s tricky, skillful putts.'},
      {context:`"It is a bit buggy and musty, but he does not mind."`, prompt:'What does "he does not mind" suggest about Brody\'s attitude toward the loft?', 
        options:['He is bothered by the conditions','He accepts the imperfect conditions without complaint','He refuses to use the loft','He wants a nicer place to rest'], answer:1,
        explain:'Saying he "does not mind" the buggy, musty conditions shows Brody is easygoing about it rather than upset.'},
      {context:`"Being a caddy for two men like Mr. Shelby and Mr. Henry is great, but it tires Brody out!"`, prompt:'What does this final line reveal about Brody\'s overall experience?', 
        options:['He regrets taking the job','The job is enjoyable but physically and mentally tiring','He wants to quit immediately','He finds the job easy and relaxing'], answer:1,
        explain:'"Great, but it tires Brody out" balances a positive feeling about the job with the honest admission that it\'s exhausting — both are true at once.'},
      {context:'Think about the whole story.', prompt:'What is one theme this story explores?', 
        options:['A job can be enjoyable even when the people you work for have quirks and demands','Golf caddies never enjoy their jobs','Rich people are always unpleasant','Brody wants a different career'], answer:0,
        explain:'Despite Mr. Shelby\'s odd comments and the tiring long days, Brody still seems to enjoy the job overall — that balance of quirks and enjoyment is the theme.'},
    ]},
  { id:'vocab', tab:'Vocab', title:"Case File 3 — Vocabulary Clues", icon:'🔍',
    intro:"Every good detective reads for clues hidden in context. Figure out what each word means the way it's used in the story.",
    type:'mc', points:10,
    questions:[
      {context:`"Brody just got a job as a caddy at a beautiful golf club."`, prompt:'What does caddy mean here?', 
        options:['A person who carries golf clubs and assists players','A type of golf club','A golf course manager','A type of ball'], answer:0,
        explain:'A caddy assists golfers, often by carrying their clubs — that\'s the job Brody just got.'},
      {context:`"Mr. Shelby has plenty of nifty clothes."`, prompt:'What does nifty mean here?', 
        options:['Old and worn out','Stylish and impressive','Dirty and torn','Plain and boring'], answer:1,
        explain:'Nifty describes something impressive or stylish — fitting with clothes that "cost a pretty penny."'},
      {context:`"He makes odd comments that don't make much sense."`, prompt:'What does odd mean here?', 
        options:['Ordinary','Strange or unusual','Angry','Quiet'], answer:1,
        explain:'Odd describes something strange or unusual — here, comments that don\'t quite make sense.'},
      {context:`"His chitchat makes things kind of fun."`, prompt:'What does chitchat mean here?', 
        options:['Serious business talk','Casual, light conversation','Silence','Arguing'], answer:1,
        explain:'Chitchat refers to casual, light conversation — not serious or heavy talk.'},
      {context:`"Mr. Shelby also has a best crony."`, prompt:'What does crony mean here?', 
        options:['A close friend or companion','A rival','A boss','A stranger'], answer:0,
        explain:'A crony is a close companion or friend — here, describing Mr. Henry\'s friendship with Mr. Shelby.'},
      {context:`"Mr. Shelby is pretty shoddy at the game."`, prompt:'What does shoddy mean here?', 
        options:['Excellent','Poor in quality or skill','Fast','Expensive'], answer:1,
        explain:'Shoddy describes poor quality or skill — contrasted right after with Mr. Henry being "quite talented."'},
      {context:`"He makes some tricky putts."`, prompt:'What does tricky mean here?', 
        options:['Simple and easy','Difficult and requiring skill','Boring','Loud'], answer:1,
        explain:'Tricky describes something difficult, requiring real skill — fitting with Mr. Henry\'s talent.'},
      {context:`"It is a bit buggy and musty."`, prompt:'What does musty mean here?', 
        options:['Freshly cleaned','Having a stale, old smell','Brightly lit','Very cold'], answer:1,
        explain:'Musty describes a stale or old smell — a common description for a rarely-aired-out loft space.'},
      {context:`"It is a good time to rest, relax, and just be lazy."`, prompt:'What does relax mean here?', 
        options:['To work hard','To rest and release tension','To argue','To hurry'], answer:1,
        explain:'Relax means to rest and ease tension — paired with "rest" and "be lazy," all describing unwinding after a long day.'},
      {context:`"Being a caddy for two men like Mr. Shelby and Mr. Henry is great, but it tires Brody out!"`, prompt:'What does tires out mean here?', 
        options:['Makes someone very energetic','Makes someone very exhausted','Makes someone angry','Makes someone bored'], answer:1,
        explain:'"Tires out" describes becoming exhausted — the natural result of a long, demanding day of caddying.'},
    ]},
  { id:'spelling', tab:'Spelling', title:"Case File 4 — Spelling Forensics", icon:'✏️',
    intro:"A detective's notes have to be exact. Listen to each word and spell it correctly to file it as evidence.",
    type:'spell', points:15,
    questions:[
      {word:'chitchat', sentence:'His chitchat makes things fun.'},
      {word:'sunset', sentence:'They golf until sunset.'},
      {word:'caddy', sentence:'Brody got a job as a caddy.'},
      {word:'silly', sentence:'Brody thinks Mr. Shelby is silly.'},
      {word:'nifty', sentence:'Mr. Shelby has nifty clothes.'},
      {word:'hobby', sentence:'Golf is their top hobby.'},
      {word:'buggy', sentence:'The loft is buggy and musty.'},
      {word:'musty', sentence:'The golf shack is musty.'},
      {word:'tricky', sentence:'Mr. Henry makes tricky putts.'},
      {word:'relax', sentence:'Brody wants to rest and relax.'},
      {word:'lazy', sentence:'It is a good time to be lazy.'},
      {word:'crony', sentence:'Mr. Shelby has a best crony.'},
    ]},
  { id:'structure', tab:'Structure', title:"Case File 5 — Structure Analysis", icon:'🧩',
    intro:"This story leans on open syllables ending in y as a vowel. Mark the sound chunks to crack the code.",
    type:'mc', points:10,
    questions:[
      {context:'chitchat', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Chitchat breaks into two syllable chunks: chit-chat, a compound word made of two closed syllables.'},
      {context:'sunset', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Sunset breaks into two syllable chunks: sun-set, a compound word made of two closed syllables.'},
      {context:'caddy', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Caddy breaks into two syllable chunks: cad-dy, a closed syllable followed by an open syllable using y as a vowel.'},
      {context:'silly', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Silly breaks into two syllable chunks: sil-ly, a closed syllable followed by an open syllable using y as a vowel.'},
      {context:'nifty', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Nifty breaks into two syllable chunks: nif-ty, a closed syllable followed by an open syllable using y as a vowel.'},
      {context:'hobby', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Hobby breaks into two syllable chunks: hob-by, a closed syllable followed by an open syllable using y as a vowel.'},
      {context:'buggy', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Buggy breaks into two syllable chunks: bug-gy, a closed syllable followed by an open syllable using y as a vowel.'},
      {context:'musty', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Musty breaks into two syllable chunks: mus-ty, a closed syllable followed by an open syllable using y as a vowel.'},
      {context:'tricky', prompt:'Which letters form the digraph in the first syllable?', options:['tr','ic','ck','ky'], answer:2,
        explain:'C and k together make one sound, /k/ — that fused single sound from two letters is what makes ck a digraph.'},
      {context:'relax', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Relax breaks into two syllable chunks: re-lax, an open syllable followed by a closed syllable.'},
    ]},
];

STORY_PACKS['brody_golf'] = {
  id: 'brody_golf',
  title: "Brody's Job at the Golf Club",
  substep: '5.3B',
  blurb: 'A caddy sizes up his two regular golfers — open syllables, closed syllables, and y as a vowel.',
  type: 'controlled', // 'controlled' (WRS-decodable) or 'authentic' (real-world text)
  keyTerms: KEY_TERMS_BRODY_GOLF,
  paragraphs: STORY_PARAGRAPHS_BRODY_GOLF,
  rounds: ROUNDS_BRODY_GOLF,
};
STORY_ORDER.push('brody_golf');
