/* ---------------------------------------------------------------
   STORY: A Chinchilla for Melissa  (WRS Substep 5.5B)
   Melissa researches her way into earning a new pet — multisyllabic words with open, closed, and VCE syllables.
   Auto-split from the original single-file build — safe to hand-edit.
   To add a NEW story, copy this whole file, rename the three consts
   and the STORY_PACKS key/id, then add a <script src="stories/yourfile.js">
   line in index.html (order in that list = order in the case picker).
   Set type to 'authentic' for real-world (non-controlled) passages — this only
   changes the badge shown on the picker card, not how rounds are built.
--------------------------------------------------------------- */
const KEY_TERMS_CHINCHILLA = ['since','family','almost','soon','paid','heard','early','feet','air','fur','enough','parents'];

const STORY_PARAGRAPHS_CHINCHILLA = [
  `Since Melissa was a just a small child, she wanted a pet. However, her family did not live in a very big home, and her mother and father were unsure about owning a pet. But, Melissa did not give up her quest. Almost every day she found a way to beg and even demand that her request be met.`,
  `One day, Melissa's lamenting paid off. Her mother responded by asking Melissa what kind of pet she wanted. Melissa was quick to say, "A chinchilla!"`,
  `Melissa's mother was at a loss. She said, "What is a chinchilla? I have never heard of such a pet!"`,
  `Melissa defended herself, "Well, I am not sure, but I do know that they are cute, and I want one."`,
  `"Hmm," began her mother, "I think that if you want a chinchilla, you should know all about them first."`,
  `Melissa knew she could not manipulate her mother anymore, so she set off to find out everything there was to know about chinchillas. Soon, she would be a pro on the topic.`,
  `Melissa was in a jam. She had been quick to advocate for a pet, but she had neglected to prepare to house one. She could not state the facts to her family. So, Melissa began to study the life of a chinchilla. She went online and began to write down all the facts.`,
  `It was astonishing to Melissa to find out early on that a chinchilla is a small rodent. They are often kept as pets, yet chinchillas can jump almost five feet into the air. They have dense, ultra-soft fur. She had also been unaware that baby chinchillas are called kits. Melissa did not stop until she felt she had enough facts to once again propose her request for such a pet.`,
  `Melissa spoke to her parents and listed all there was to know about owning a chinchilla. She commented that chinchillas like to snack on twigs and grass as they sit on their hind legs. Melissa's mother and father learned that since their fur used to be in demand, the chinchillas are now extinct in some parts of the world.`,
  `It would take a lot of work to care for a chinchilla. They require dust baths and must live where there is a lot of shade. In the end, her mother and father told Melissa that her study of the chinchilla was impressive. They felt that she now had the wisdom to care for one.`,
  `At last! Melissa would get her pet!`,
];

const ROUNDS_CHINCHILLA = [
  { id:'sequence', tab:'Timeline', title:"Case File 1 — Timeline Reconstruction", icon:'🗺️',
    intro:"Drag the evidence into the correct order to rebuild Melissa's quest for a pet.",
    type:'sequence', points:5,
    sets:[
      { label:'Asking for a pet — put these in order', events:[
          "Melissa begs and demands a pet almost every day.",
          "Melissa's mother finally asks what kind of pet she wants.",
          "Melissa says she wants a chinchilla.",
          "Melissa's mother says she has never heard of one.",
      ]},
      { label:'Doing the research — put these in order', events:[
          "Melissa's mother tells her to learn all about chinchillas first.",
          "Melissa goes online and studies the facts.",
          "Melissa learns chinchillas can jump almost five feet.",
          "Melissa's parents say her research made her ready for a pet.",
      ]},
    ]},
  { id:'inference', tab:'Inference', title:"Case File 2 — Detective Inference", icon:'🧠',
    intro:"The best clues aren't always written in the text. Read between the lines to solve these.",
    type:'mc', points:12,
    questions:[
      {context:`"But, Melissa did not give up her quest. Almost every day she found a way to beg and even demand that her request be met."`, prompt:'What does this tell you about Melissa\'s personality?', 
        options:['She gives up easily','She is persistent and determined about things she wants','She doesn\'t care about having a pet','She is easily distracted'], answer:1,
        explain:'Trying "almost every day" without giving up shows real persistence and determination toward getting what she wants.'},
      {context:`"Melissa's mother was at a loss. She said, 'What is a chinchilla? I have never heard of such a pet!'"`, prompt:'What does "at a loss" tell you about Melissa\'s mother\'s reaction?', 
        options:['She was excited and knew exactly what to say','She was confused and unsure how to respond','She was angry at Melissa','She had expected this exact request'], answer:1,
        explain:'"At a loss" describes confusion or uncertainty — the mother genuinely doesn\'t know what a chinchilla is, which surprises her.'},
      {context:`"Melissa knew she could not manipulate her mother anymore, so she set off to find out everything there was to know about chinchillas."`, prompt:'What does this tell you about the shift in Melissa\'s approach?', 
        options:['She gave up on getting a pet','She switched from begging to doing real research','She decided to manipulate her mother even more','She asked her father instead'], answer:1,
        explain:'The word "so" connects realizing manipulation won\'t work to setting off and researching instead — a real change in her strategy.'},
      {context:`"Melissa was in a jam. She had been quick to advocate for a pet, but she had neglected to prepare to house one."`, prompt:'What problem does "in a jam" describe?', 
        options:['She was in physical danger','She was in a difficult situation because she wasn\'t actually prepared','She was too excited to think','She had lost her pet already'], answer:1,
        explain:'"In a jam" describes a difficult spot — here, she pushed hard for a pet without actually being ready to explain how she\'d care for one.'},
      {context:`"It was astonishing to Melissa to find out early on that a chinchilla is a small rodent."`, prompt:'What does "astonishing" suggest about Melissa\'s prior knowledge?', 
        options:['She already knew everything about chinchillas','She was genuinely surprised, meaning she knew very little beforehand','She didn\'t care about the fact','She thought it was untrue'], answer:1,
        explain:'Being "astonished" by a basic fact suggests Melissa started her research knowing very little about chinchillas.'},
      {context:`"Melissa did not stop until she felt she had enough facts to once again propose her request for such a pet."`, prompt:'What does this tell you about how Melissa approached her second request?', 
        options:['She rushed into asking without any preparation','She made sure she was well-prepared before asking again','She gave up on asking a second time','She asked her father instead of her mother'], answer:1,
        explain:'"Did not stop until she felt she had enough facts" shows she deliberately built up her knowledge before trying again, rather than rushing in.'},
      {context:`"Melissa's mother and father learned that since their fur used to be in demand, the chinchillas are now extinct in some parts of the world."`, prompt:'What connection is this sentence making?', 
        options:['Chinchillas became extinct because people wanted their fur','Chinchillas are extinct because they are unpopular pets','Chinchillas are extinct due to a disease','Chinchillas were never common anywhere'], answer:0,
        explain:'The word "since" links the fur being "in demand" to the chinchillas being "now extinct" in some places — showing cause and effect.'},
      {context:`"In the end, her mother and father told Melissa that her study of the chinchilla was impressive. They felt that she now had the wisdom to care for one."`, prompt:'What changed their minds about letting Melissa have the pet?', 
        options:['They were tired of her asking','Her thorough research proved she understood how to responsibly care for one','They found the pet on sale','Her father always wanted a chinchilla'], answer:1,
        explain:'It\'s specifically her "study" and resulting "wisdom" that convinced them — her preparation, not persistence alone, earned their trust.'},
      {context:'Think about the whole story.', prompt:'What is one theme this story explores?', 
        options:['Persistence alone is always enough to get what you want','Genuine responsibility, shown through real preparation, earns trust','Parents should say no to every request','Research is a waste of time'], answer:1,
        explain:'Melissa\'s early demanding didn\'t work — it was only after she genuinely researched and prepared that her parents trusted her with a pet, which points to responsibility earning trust.'},
    ]},
  { id:'vocab', tab:'Vocab', title:"Case File 3 — Vocabulary Clues", icon:'🔍',
    intro:"Every good detective reads for clues hidden in context. Figure out what each word means the way it's used in the story.",
    type:'mc', points:10,
    questions:[
      {context:`"But, Melissa did not give up her quest."`, prompt:'What does quest mean here?', 
        options:['A type of pet','A determined search or pursuit of a goal','A chore','A game'], answer:1,
        explain:'A quest is a determined pursuit of a goal — here, Melissa\'s ongoing pursuit of getting a pet.'},
      {context:`"One day, Melissa's lamenting paid off."`, prompt:'What does lamenting mean here?', 
        options:['Celebrating happily','Complaining or expressing sorrow persistently','Studying quietly','Sleeping'], answer:1,
        explain:'Lamenting describes persistent complaining or expressing unhappiness — describing Melissa\'s repeated pleas for a pet.'},
      {context:`"Melissa knew she could not manipulate her mother anymore."`, prompt:'What does manipulate mean here?', 
        options:['To help someone directly','To influence or control someone unfairly to get a desired outcome','To ask politely once','To ignore someone'], answer:1,
        explain:'Manipulate means to unfairly influence or control someone\'s decisions — here, Melissa realizing that tactic won\'t work anymore.'},
      {context:`"She had been quick to advocate for a pet, but she had neglected to prepare to house one."`, prompt:'What does advocate mean here?', 
        options:['To argue against something','To speak strongly in favor of something','To forget about something','To research something'], answer:1,
        explain:'To advocate means to argue or speak strongly in favor of something — here, in favor of getting a pet.'},
      {context:`"She had neglected to prepare to house one."`, prompt:'What does neglected mean here?', 
        options:['Carefully completed','Failed to do or take care of something','Enjoyed doing something','Finished early'], answer:1,
        explain:'Neglected means failing to do or take care of something — Melissa hadn\'t prepared to actually house a pet.'},
      {context:`"It was astonishing to Melissa to find out early on that a chinchilla is a small rodent."`, prompt:'What does rodent mean here?', 
        options:['A type of bird','A small gnawing mammal','A reptile','A type of fish'], answer:1,
        explain:'A rodent is a small gnawing mammal — a category that includes chinchillas, mice, and similar animals.'},
      {context:`"They have dense, ultra-soft fur."`, prompt:'What does dense mean here?', 
        options:['Thin and see-through','Thick and closely packed','Rough and scratchy','Colorful'], answer:1,
        explain:'Dense describes something thick and closely packed — here, describing how thick the chinchilla\'s fur grows.'},
      {context:`"Melissa did not stop until she felt she had enough facts to once again propose her request."`, prompt:'What does propose mean here?', 
        options:['To refuse something','To formally suggest or put forward an idea','To hide something','To forget something'], answer:1,
        explain:'Propose means to formally suggest or put something forward — here, putting the idea of getting a pet in front of her parents again.'},
      {context:`"The chinchillas are now extinct in some parts of the world."`, prompt:'What does extinct mean here?', 
        options:['Extremely common','No longer existing in a particular place','Very small','Newly discovered'], answer:1,
        explain:'Extinct means no longer existing — here, describing chinchillas that have disappeared from certain regions.'},
      {context:`"They felt that she now had the wisdom to care for one."`, prompt:'What does wisdom mean here?', 
        options:['Money to spend','Good judgment and knowledge gained through learning','Physical strength','A type of pet'], answer:1,
        explain:'Wisdom refers to good judgment and knowledge — here, the understanding Melissa gained through her research.'},
    ]},
  { id:'spelling', tab:'Spelling', title:"Case File 4 — Spelling Forensics", icon:'✏️',
    intro:"A detective's notes have to be exact. Listen to each word and spell it correctly to file it as evidence.",
    type:'spell', points:15,
    questions:[
      {word:'chinchilla', sentence:'Melissa wants a chinchilla.'},
      {word:'lamenting', sentence:'Her lamenting finally paid off.'},
      {word:'manipulate', sentence:'She could not manipulate her mother.'},
      {word:'astonishing', sentence:'It was astonishing to learn the facts.'},
      {word:'rodent', sentence:'A chinchilla is a small rodent.'},
      {word:'advocate', sentence:'She was quick to advocate for a pet.'},
      {word:'neglected', sentence:'She neglected to prepare first.'},
      {word:'propose', sentence:'She would propose her request again.'},
      {word:'extinct', sentence:'Chinchillas are extinct in some places.'},
      {word:'wisdom', sentence:'She now had the wisdom to care for one.'},
    ]},
  { id:'structure', tab:'Structure', title:"Case File 5 — Structure Analysis", icon:'🧩',
    intro:"This story mixes open, closed, and VCE syllables across longer words. Mark the sound chunks to crack the code.",
    type:'mc', points:10,
    questions:[
      {context:'chinchilla', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:2,
        explain:'Chinchilla breaks into three syllable chunks: chin-chil-la.'},
      {context:'lamenting', prompt:'Which letters form the welded chunk?', options:['la','men','ing','nt'], answer:2,
        explain:'"Ing" is a welded sound taught as one unit — it stays glued together wherever it appears, including inside lamenting.'},
      {context:'manipulate', prompt:'How many syllables does this word have?', options:['2','3','4','5'], answer:2,
        explain:'Manipulate breaks into four syllable chunks: ma-nip-u-late, ending in a VCE syllable.'},
      {context:'astonishing', prompt:'How many syllables does this word have?', options:['2','3','4','5'], answer:2,
        explain:'Astonishing breaks into four syllable chunks: a-ston-ish-ing.'},
      {context:'rodent', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Rodent breaks into two syllable chunks: ro-dent, an open syllable followed by a closed syllable.'},
      {context:'advocate', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:2,
        explain:'Advocate breaks into three syllable chunks: ad-vo-cate, ending in a VCE syllable.'},
      {context:'neglected', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:2,
        explain:'Neglected breaks into three syllable chunks: ne-glect-ed.'},
      {context:'propose', prompt:'What syllable type is the second syllable, "pose"?', options:['Open syllable','VCE (vowel-consonant-e)','Closed syllable','Welded'], answer:1,
        explain:'"Pose" has a vowel, then a consonant, then a silent e — that pattern is a VCE syllable, giving the o its long sound.'},
      {context:'extinct', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Extinct breaks into two syllable chunks: ex-tinct, both closed syllables.'},
      {context:'wisdom', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Wisdom breaks into two syllable chunks: wis-dom, both closed syllables.'},
    ]},
];

STORY_PACKS['chinchilla_melissa'] = {
  id: 'chinchilla_melissa',
  title: "A Chinchilla for Melissa",
  substep: '5.5B',
  blurb: 'Melissa researches her way into earning a new pet — multisyllabic words with open, closed, and VCE syllables.',
  type: 'controlled', // 'controlled' (WRS-decodable) or 'authentic' (real-world text)
  keyTerms: KEY_TERMS_CHINCHILLA,
  paragraphs: STORY_PARAGRAPHS_CHINCHILLA,
  rounds: ROUNDS_CHINCHILLA,
};
STORY_ORDER.push('chinchilla_melissa');
