/* ---------------------------------------------------------------
   STORY: Glen and the Gull Have Lunch  (WRS Substep 2.4AB)
   A day at the beach — closed syllables, blends, and digraphs.
   Auto-split from the original single-file build — safe to hand-edit.
   To add a NEW story, copy this whole file, rename the three consts
   and the STORY_PACKS key/id, then add a <script src="stories/yourfile.js">
   line in index.html (order in that list = order in the case picker).
   Set type to 'authentic' for real-world (non-controlled) passages — this only
   changes the badge shown on the picker card, not how rounds are built.
--------------------------------------------------------------- */
const KEY_TERMS_GLEN_GULL = ['out','front','about','only','their','day','eat','while','like','good','look','goes'];

const STORY_PARAGRAPHS_GLEN_GULL = [
  `Glen sits in the sand with his mom and dad. They have been there all day. Mom holds a bag out in front of Glen and he picks out a crisp, fat shrimp to eat. Then he sips some of his drink. Dad has clams to snack on while he squints in the sun. Glen thinks the clams smell like a skunk and he will not have any.`,
  `By a clump of plants, Glen spots a small gull coming into the wet sand. Glen dashes up to the gull to get a good look. Now, this gull just goes about his hunt for clams in the mud. Only when he finds a clam does the gull lift his wings and blast off.`,
  `Glen thinks, "That must be his lunch. Dad and gulls can have their clams, but I will stick to shrimp for my lunch!"`,
];

const ROUNDS_GLEN_GULL = [
  { id:'sequence', tab:'Timeline', title:"Case File 1 — Timeline Reconstruction", icon:'🗺️',
    intro:"Drag the evidence into the correct order to rebuild Glen's afternoon at the beach.",
    type:'sequence', points:5,
    sets:[
      { label:'Lunch on the sand — put these in order', events:[
          "Glen sits in the sand with his mom and dad.",
          "Mom holds the bag out and Glen picks a shrimp to eat.",
          "Glen sips some of his drink.",
          "Dad snacks on clams while Glen decides he won't have any.",
      ]},
      { label:'Meeting the gull — put these in order', events:[
          "Glen spots a small gull by a clump of plants.",
          "Glen dashes up to the gull to get a good look.",
          "The gull hunts for clams in the mud.",
          "The gull finds a clam and blasts off with it.",
      ]},
    ]},
  { id:'inference', tab:'Inference', title:"Case File 2 — Detective Inference", icon:'🧠',
    intro:"The best clues aren't always written in the text. Read between the lines to solve these.",
    type:'mc', points:12,
    questions:[
      {context:`"They have been there all day."`, prompt:'What does this tell you about Glen\'s family?', 
        options:['They just arrived at the beach','They\'ve been at the beach for a long time already','They are leaving soon','They come to the beach once a year'], answer:1,
        explain:'"All day" is the clue — it tells you they arrived a long time ago and have stayed there since, not that they just got there.'},
      {context:`"Mom holds a bag out in front of Glen and he picks out a crisp, fat shrimp to eat."`, prompt:'What can you tell about the bag?', 
        options:['It holds cold drinks only','It holds food for the family\'s lunch','It is empty','It holds sand toys'], answer:1,
        explain:'Glen picks a shrimp "to eat" straight out of the bag — that tells you the bag is holding their food.'},
      {context:`"Glen thinks the clams smell like a skunk and he will not have any."`, prompt:'Why won\'t Glen eat the clams?', 
        options:['He is full from the shrimp','He thinks they smell bad','His mom told him not to','He does not like his dad'], answer:1,
        explain:'The text gives the reason directly — comparing the smell to a skunk explains exactly why Glen turns the clams down.'},
      {context:`"Dad has clams to snack on while he squints in the sun."`, prompt:'Why is Dad squinting?', 
        options:['He is confused','The bright sun is in his eyes','He is looking for the gull','He does not like clams'], answer:1,
        explain:'Squinting happens "in the sun" — that\'s the direct cause. Bright light naturally makes people squint.'},
      {context:`"By a clump of plants, Glen spots a small gull coming into the wet sand."`, prompt:'Where does Glen first notice the gull?', 
        options:['Near a clump of plants','In the water','Under a towel','Next to the food bag'], answer:0,
        explain:'The location is given right at the start of the sentence — "by a clump of plants" is where Glen is standing when he spots the gull.'},
      {context:`"Glen dashes up to the gull to get a good look."`, prompt:'What does "dashes" suggest about how Glen moves?', 
        options:['He walks slowly','He moves quickly, eager to see the gull','He crawls on the sand','He stays still'], answer:1,
        explain:'Dashing is a fast movement — paired with wanting "a good look," it shows Glen is eager and excited, not slow or hesitant.'},
      {context:`"Now, this gull just goes about his hunt for clams in the mud."`, prompt:'What does this tell you about the gull\'s reaction to Glen?', 
        options:['The gull is scared and flies away','The gull ignores Glen and keeps hunting','The gull attacks Glen','The gull follows Glen home'], answer:1,
        explain:'"Just goes about his hunt" means the gull keeps doing what it was doing — it isn\'t bothered enough by Glen to stop or flee.'},
      {context:`"Only when he finds a clam does the gull lift his wings and blast off."`, prompt:'What finally makes the gull fly away?', 
        options:['Glen getting too close','Finding a clam','A loud noise','The tide coming in'], answer:1,
        explain:'The sentence structure says the gull flies "only when he finds a clam" — finding food is the trigger for it to take off.'},
      {context:`"Dad and gulls can have their clams, but I will stick to shrimp for my lunch!"`, prompt:'What is Glen deciding here?', 
        options:['To try a clam after all','To keep eating shrimp instead of clams','To stop eating altogether','To share his shrimp with the gull'], answer:1,
        explain:'"Stick to shrimp" means Glen is choosing to keep eating what he already likes, while leaving the clams to his dad and the gulls.'},
      {context:'Think about the whole story.', prompt:'What is one theme this story explores?', 
        options:['Different creatures like different foods','Beaches are dangerous places','You should always try new foods','Gulls cannot find their own food'], answer:0,
        explain:'Glen likes shrimp, Dad and the gull both go for clams — the story is built around each character/creature having its own food preference.'},
    ]},
  { id:'vocab', tab:'Vocab', title:"Case File 3 — Vocabulary Clues", icon:'🔍',
    intro:"Every good detective reads for clues hidden in context. Figure out what each word means the way Glen used it in the story.",
    type:'mc', points:10,
    questions:[
      {context:`"He picks out a crisp, fat shrimp to eat."`, prompt:'What does crisp mean here?', 
        options:['Soft and mushy','Firm and fresh','Burnt black','Ice cold'], answer:1,
        explain:'Crisp describes food that is fresh and firm, the opposite of soft or mushy — it\'s a positive detail about the shrimp Glen picked.'},
      {context:`"Dad has clams to snack on while he squints in the sun."`, prompt:'What does squints mean here?', 
        options:['Closes his eyes partway against bright light','Falls asleep','Looks far away','Waves his hand'], answer:0,
        explain:'Squinting happens when bright sunlight makes someone partly close their eyes — the phrase "in the sun" is the clue.'},
      {context:`"Glen thinks the clams smell like a skunk."`, prompt:'What does this comparison tell you about the smell?', 
        options:['It smells sweet','It smells very bad','It has no smell','It smells like the ocean'], answer:1,
        explain:'A skunk is famous for its strong, unpleasant smell — comparing the clams to one tells you Glen thinks they smell bad.'},
      {context:`"By a clump of plants, Glen spots a small gull."`, prompt:'What does clump mean here?', 
        options:['A single leaf','A small, bunched-together group','A tall tree','An empty patch of sand'], answer:1,
        explain:'A clump is a small cluster of things bunched together — here, a group of plants growing close together.'},
      {context:`"Glen dashes up to the gull to get a good look."`, prompt:'What does dashes mean here?', 
        options:['Walks slowly','Runs quickly','Crawls','Stands still'], answer:1,
        explain:'Dashing means moving fast — it shows Glen hurrying eagerly toward the gull.'},
      {context:`"This gull just goes about his hunt for clams in the mud."`, prompt:'What does hunt mean here?', 
        options:['A nap','A search for food','A game','A race'], answer:1,
        explain:'"Hunt for clams" describes the gull searching for food, not playing or resting.'},
      {context:`"Only when he finds a clam does the gull lift his wings and blast off."`, prompt:'What does blast off mean here?', 
        options:['Take off suddenly and quickly','Land softly','Dig into the sand','Swim away'], answer:0,
        explain:'"Blast off" describes a fast, sudden launch — like a rocket taking off — showing how quickly the gull flies away.'},
      {context:`"I will stick to shrimp for my lunch!"`, prompt:'What does stick to mean here?', 
        options:['Glue something down','Keep choosing the same thing','Throw something away','Share with someone'], answer:1,
        explain:'"Stick to shrimp" means Glen is going to keep choosing shrimp instead of switching to something else, like the clams.'},
      {context:`"Mom holds a bag out in front of Glen."`, prompt:'What does holds out mean here?', 
        options:['Hides something','Extends something toward someone','Drops something','Puts something away'], answer:1,
        explain:'Holding a bag "out in front of" Glen means Mom is extending it toward him so he can reach in and pick something.'},
      {context:`"Now, this gull just goes about his hunt."`, prompt:'What does the word now signal in this sentence?', 
        options:['A shift to a new moment in the action','The story is ending','A flashback to earlier','A change of location only'], answer:0,
        explain:'"Now" here marks the moment the focus shifts to what the gull does next, moving the action forward in time.'},
    ]},
  { id:'spelling', tab:'Spelling', title:"Case File 4 — Spelling Forensics", icon:'✏️',
    intro:"A detective's notes have to be exact. Listen to each word and spell it correctly to file it as evidence.",
    type:'spell', points:15,
    questions:[
      {word:'front', sentence:'Mom holds a bag out in front of Glen.'},
      {word:'crisp', sentence:'He picks out a crisp shrimp.'},
      {word:'shrimp', sentence:'Glen eats a fat shrimp.'},
      {word:'drink', sentence:'Glen sips some of his drink.'},
      {word:'snack', sentence:'Dad has clams to snack on.'},
      {word:'skunk', sentence:'The clams smell like a skunk.'},
      {word:'clump', sentence:'Glen stands by a clump of plants.'},
      {word:'plants', sentence:'The clump of plants was by the sand.'},
      {word:'spots', sentence:'Glen spots a small gull.'},
      {word:'blast', sentence:'The gull will blast off.'},
      {word:'stick', sentence:'I will stick to shrimp for lunch.'},
      {word:'gull', sentence:'The gull hunts for clams in the mud.'},
    ]},
  { id:'structure', tab:'Structure', title:"Case File 5 — Structure Analysis", icon:'🧩',
    intro:"Every word is a piece of evidence with structure. Mark the blends, digraphs, and sounds to crack the code.",
    type:'mc', points:10,
    questions:[
      {context:'front', prompt:'Which letters form the beginning consonant blend?', options:['fr','on','nt','ro'], answer:0,
        explain:'You can still hear both /f/ and /r/ blended together at the start of front, so fr is the blend.'},
      {context:'crisp', prompt:'Which letters form the beginning blend?', options:['cr','is','sp','ri'], answer:0,
        explain:'/c/ and /r/ stay separately heard at the start of crisp, blended together — that makes cr the blend.'},
      {context:'shrimp', prompt:'Which letters form the beginning digraph?', options:['sh','ri','mp','hr'], answer:0,
        explain:'S and h together make one new sound, /sh/, instead of two separate sounds — that\'s what makes it a digraph.'},
      {context:'drink', prompt:'Which letters form the beginning blend?', options:['dr','in','nk','ri'], answer:0,
        explain:'/d/ and /r/ are both still heard blended together at the start of drink — that\'s the blend.'},
      {context:'drink', prompt:'Which letters form the welded ending?', options:['dr','in','ink','ri'], answer:2,
        explain:'"Ink" is a welded sound — the i, n, and k glue together into one chunk that\'s always taught and read as a unit.'},
      {context:'skunk', prompt:'Which letters form the welded ending?', options:['sk','un','unk','nk'], answer:2,
        explain:'"Unk" is a welded sound, just like ink and ank — the vowel and the two consonants after it are always chunked together.'},
      {context:'snack', prompt:'Which letters form the ending digraph?', options:['sn','ac','ck','na'], answer:2,
        explain:'C and k together make one sound, /k/ — that single new sound from two letters is what makes ck a digraph.'},
      {context:'plants', prompt:'Which letters form the welded chunk?', options:['pl','an','ts','la'], answer:1,
        explain:'"An" is a welded sound taught early on — it stays glued together as one chunk wherever it shows up in a word, including inside plants.'},
      {context:'blast', prompt:'Which letters form the beginning blend?', options:['bl','as','st','la'], answer:0,
        explain:'/b/ and /l/ are both still heard blended together at the start of blast, making bl the blend.'},
      {context:'stick', prompt:'How many sounds are in this word? (st / i / ck)', options:['3','4','5','2'], answer:1,
        explain:'Count each separate sound: st is a blend of 2 sounds (/s/ /t/), i is 1 sound, and ck is a digraph making 1 sound (/k/) — 2+1+1 = 4 sounds total.'},
    ]},
];

STORY_PACKS['glen_and_gull'] = {
  id: 'glen_and_gull',
  title: "Glen and the Gull Have Lunch",
  substep: '2.4AB',
  blurb: 'A day at the beach — Glen picks his lunch while a gull hunts for its own.',
  type: 'controlled', // 'controlled' (WRS-decodable) or 'authentic' (real-world text)
  keyTerms: KEY_TERMS_GLEN_GULL,
  paragraphs: STORY_PARAGRAPHS_GLEN_GULL,
  rounds: ROUNDS_GLEN_GULL,
};
STORY_ORDER.push('glen_and_gull');
