/* ---------------------------------------------------------------
   STORY: A Day with Grandma  (WRS Substep 5.5AB)
   Two sisters make the long drive to visit Grandma — open syllable exceptions (schwa) in multisyllabic words.
   Auto-split from the original single-file build — safe to hand-edit.
   To add a NEW story, copy this whole file, rename the three consts
   and the STORY_PACKS key/id, then add a <script src="stories/yourfile.js">
   line in index.html (order in that list = order in the case picker).
   Set type to 'authentic' for real-world (non-controlled) passages — this only
   changes the badge shown on the picker card, not how rounds are built.
--------------------------------------------------------------- */
const KEY_TERMS_GRANDMA_DAY = ['since','early','family','almost','soon','a.m.'];

const STORY_PARAGRAPHS_GRANDMA_DAY = [
  `Emma and her sister, Melissa, made plans to visit Grandma in Atlanta. Since the two gals wanted to get on their way before the traffic rush, they set their clocks to wake up early. They had bananas and a granola snack. Then, they fed the family pets before they set off on their long trip across the state.`,
  `The drive to Atlanta was full of splendid things. The abundant red hills were impressive, and Emma thought they should look at the beautiful landscape for a while. However, Melissa reminded her about their plan to spend the entire day with Grandma. Extra stops on their drive would only make them late!`,
  `It was almost nine a.m. when they pulled up to Grandma's small house. Grandma was a tall thin woman with a kind smile. She met Emma and Melissa on the front step with hugs for both of them.`,
  `The three women were so much alike! They spent the day talking about all kinds of things. Grandma made sure Emma and Melissa had plenty of snacks. Before long, it was time to go home. Emma and Melissa told Grandma that they would be back to spend the day with her very soon.`,
];

const ROUNDS_GRANDMA_DAY = [
  { id:'sequence', tab:'Timeline', title:"Case File 1 — Timeline Reconstruction", icon:'🗺️',
    intro:"Drag the evidence into the correct order to rebuild Emma and Melissa's day.",
    type:'sequence', points:5,
    sets:[
      { label:'Before the visit — put these in order', events:[
          "Emma and Melissa wake up early to beat traffic.",
          "They eat bananas and a granola snack.",
          "They feed the family pets before leaving.",
          "Emma wants to stop and look at the landscape.",
      ]},
      { label:"At Grandma's house — put these in order", events:[
          "Melissa reminds Emma about their plan to see Grandma.",
          "They pull up to Grandma's house almost at nine a.m.",
          "Grandma greets them with hugs on the front step.",
          "They promise Grandma they'll be back again soon.",
      ]},
    ]},
  { id:'inference', tab:'Inference', title:"Case File 2 — Detective Inference", icon:'🧠',
    intro:"The best clues aren't always written in the text. Read between the lines to solve these.",
    type:'mc', points:12,
    questions:[
      {context:`"Since the two gals wanted to get on their way before the traffic rush, they set their clocks to wake up early."`, prompt:'Why did they wake up early?', 
        options:['They wanted to avoid heavy traffic','They were excited and couldn\'t sleep','Grandma asked them to','They were running late already'], answer:0,
        explain:'The sentence directly states the reason — "since" they wanted to beat the traffic rush, they woke up early to avoid it.'},
      {context:`"Emma thought they should look at the beautiful landscape for a while."`, prompt:'What does this tell you about Emma\'s priorities during the drive?', 
        options:['She wants to get to Grandma\'s as fast as possible','She is tempted to slow down and enjoy the scenery','She dislikes road trips','She wants to turn around and go home'], answer:1,
        explain:'Wanting to "look at the beautiful landscape for a while" shows Emma is drawn to slowing down and enjoying the view.'},
      {context:`"Melissa reminded her about their plan to spend the entire day with Grandma. Extra stops on their drive would only make them late!"`, prompt:'What does this tell you about Melissa\'s priorities compared to Emma\'s?', 
        options:['Melissa also wants to stop and look at scenery','Melissa is more focused on staying on schedule than sightseeing','Melissa doesn\'t want to visit Grandma at all','Melissa agrees they should stop'], answer:1,
        explain:'Melissa\'s reminder about their plan and warning about lateness shows she prioritizes staying on schedule over Emma\'s wish to sightsee.'},
      {context:`"Grandma was a tall thin woman with a kind smile."`, prompt:'What impression does this description create of Grandma?', 
        options:['She seems unfriendly and distant','She seems warm and welcoming','She seems tired and sad','She seems strict and serious'], answer:1,
        explain:'A "kind smile" is a warm, welcoming detail — it sets a friendly first impression of Grandma before we even see her greet the girls.'},
      {context:`"She met Emma and Melissa on the front step with hugs for both of them."`, prompt:'What does this greeting suggest about the relationship between Grandma and her granddaughters?', 
        options:['They rarely see each other and are awkward together','They have a warm, affectionate relationship','Grandma is upset with them','They just met for the first time'], answer:1,
        explain:'Greeting both girls with hugs right at the door shows genuine affection and closeness in the relationship.'},
      {context:`"The three women were so much alike!"`, prompt:'What does this line suggest about the family?', 
        options:['They constantly argue and disagree','Emma, Melissa, and Grandma share similar traits or personalities','They look nothing alike','Grandma is very different from her granddaughters'], answer:1,
        explain:'"So much alike" points to shared traits between the three women — a strong resemblance in personality or character, not difference.'},
      {context:`"Grandma made sure Emma and Melissa had plenty of snacks."`, prompt:'What does this small detail suggest about Grandma as a host?', 
        options:['She is neglectful of her guests','She is attentive and caring toward her granddaughters','She dislikes cooking or preparing food','She forgot to plan for their visit'], answer:1,
        explain:'Making sure her granddaughters "had plenty" of snacks is a caring, attentive gesture from a grandmother hosting her family.'},
      {context:`"They would be back to spend the day with her very soon."`, prompt:'What does this ending suggest about how the visit went?', 
        options:['The visit went poorly and they don\'t want to return','The visit was enjoyable enough that they want to repeat it soon','They forgot to say goodbye','They are moving away from Grandma'], answer:1,
        explain:'Promising to come back "very soon" only makes sense if the visit was a positive experience worth repeating.'},
      {context:'Think about the whole story.', prompt:'What is one theme this story explores?', 
        options:['Family visits require careful planning, but the connection is worth the effort','Long drives are never worthwhile','Grandparents are difficult to visit','Family members rarely get along'], answer:0,
        explain:'The story spends real time on the planning and drive — waking early, staying on schedule — all in service of a warm, valued visit with Grandma, which is the point of the theme.'},
    ]},
  { id:'vocab', tab:'Vocab', title:"Case File 3 — Vocabulary Clues", icon:'🔍',
    intro:"Every good detective reads for clues hidden in context. Figure out what each word means the way it's used in the story.",
    type:'mc', points:10,
    questions:[
      {context:`"They set their clocks to wake up early."`, prompt:'What does early mean here?', 
        options:['Later than usual','Before the usual or expected time','At the exact usual time','Very late at night'], answer:1,
        explain:'Early means before the usual time — here, waking up sooner than normal to beat traffic.'},
      {context:`"The drive to Atlanta was full of splendid things."`, prompt:'What does splendid mean here?', 
        options:['Boring and dull','Magnificent and impressive','Frightening','Confusing'], answer:1,
        explain:'Splendid describes something magnificent or impressive — fitting with the scenic drive described next.'},
      {context:`"The abundant red hills were impressive."`, prompt:'What does abundant mean here?', 
        options:['Very scarce or rare','Existing in large quantities','Very small','Hidden from view'], answer:1,
        explain:'Abundant means existing in large amounts — describing hills that appeared frequently and plentifully along the drive.'},
      {context:`"Emma thought they should look at the beautiful landscape for a while."`, prompt:'What does landscape mean here?', 
        options:['A type of vehicle','A wide view of natural scenery','A type of food','A road sign'], answer:1,
        explain:'Landscape refers to a broad view of natural scenery — here, the hills and land they were driving through.'},
      {context:`"Melissa reminded her about their plan to spend the entire day with Grandma."`, prompt:'What does entire mean here?', 
        options:['Part of','The whole, complete amount','A short time','None of'], answer:1,
        explain:'Entire means the whole or complete amount — the full day, not just part of it, was meant for Grandma.'},
      {context:`"Extra stops on their drive would only make them late!"`, prompt:'What does extra mean here?', 
        options:['Necessary and required','Additional, beyond what was planned','The only stop','A shortcut'], answer:1,
        explain:'Extra describes something additional beyond the original plan — unplanned stops that weren\'t part of their schedule.'},
      {context:`"It was almost nine a.m. when they pulled up to Grandma's small house."`, prompt:'What does pulled up mean here?', 
        options:['Drove away quickly','Arrived and stopped the car','Got out and walked','Turned around'], answer:1,
        explain:'"Pulled up" describes a vehicle arriving and coming to a stop — here, at Grandma\'s house.'},
      {context:`"The three women were so much alike!"`, prompt:'What does alike mean here?', 
        options:['Very different from each other','Similar to one another','Angry with each other','Strangers to each other'], answer:1,
        explain:'Alike means similar — the three women shared noticeable similarities in traits or personality.'},
      {context:`"Grandma made sure Emma and Melissa had plenty of snacks."`, prompt:'What does plenty mean here?', 
        options:['A very small amount','A large, more-than-enough amount','None at all','Just barely enough'], answer:1,
        explain:'Plenty means an ample, more-than-sufficient amount — Grandma made sure there was more than enough for her granddaughters.'},
      {context:`"Before long, it was time to go home."`, prompt:'What does before long mean here?', 
        options:['After a very long time','After a relatively short time','Immediately, with no delay','Never'], answer:1,
        explain:'"Before long" describes a relatively short passage of time — the visit felt like it went by quickly before it was time to leave.'},
    ]},
  { id:'spelling', tab:'Spelling', title:"Case File 4 — Spelling Forensics", icon:'✏️',
    intro:"A detective's notes have to be exact. Listen to each word and spell it correctly to file it as evidence.",
    type:'spell', points:15,
    questions:[
      {word:'family', sentence:'They fed the family pets.'},
      {word:'almost', sentence:'It was almost nine a.m.'},
      {word:'abundant', sentence:'The abundant hills were impressive.'},
      {word:'impressive', sentence:'The red hills were impressive.'},
      {word:'entire', sentence:'They wanted the entire day with Grandma.'},
      {word:'banana', sentence:'They had a banana for breakfast.'},
      {word:'granola', sentence:'They had a granola snack.'},
      {word:'landscape', sentence:'Emma looked at the beautiful landscape.'},
      {word:'splendid', sentence:'The drive was full of splendid things.'},
      {word:'extra', sentence:'Extra stops would make them late.'},
    ]},
  { id:'structure', tab:'Structure', title:"Case File 5 — Structure Analysis", icon:'🧩',
    intro:"This story features the open syllable exception, where an open syllable makes the schwa sound instead of its long vowel. Mark the sound chunks to crack the code.",
    type:'mc', points:10,
    questions:[
      {context:'family', prompt:'The first syllable, "fa," is open, but its vowel makes the schwa sound instead of a long a. What is this pattern called?', options:['A closed syllable','An open syllable exception','A welded sound','A VCE syllable'], answer:1,
        explain:'When an open syllable doesn\'t make its expected long vowel sound and instead makes the schwa /ə/ sound, that\'s called an open syllable exception.'},
      {context:'almost', prompt:'The first syllable, "al," makes the schwa sound rather than its expected sound. What is this pattern called?', options:['A closed syllable','An open syllable exception','A digraph','A blend'], answer:1,
        explain:'Almost shows the same open syllable exception pattern as family — the vowel in the first syllable reduces to a schwa sound.'},
      {context:'abundant', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:2,
        explain:'Abundant breaks into three syllable chunks: a-bun-dant, with the first syllable making a schwa sound.'},
      {context:'impressive', prompt:'Which letters form the welded suffix?', options:['im','pres','ive','ss'], answer:2,
        explain:'"Ive" is a welded suffix — it glues together into one chunk that\'s always read as a unit, just like in destructive and protective.'},
      {context:'entire', prompt:'What syllable type is the second syllable, "tire"?', options:['Open syllable','VCE (vowel-consonant-e)','Closed syllable','Welded'], answer:1,
        explain:'"Tire" has a vowel, then a consonant, then a silent e — that pattern is a VCE syllable, giving the i its long sound.'},
      {context:'banana', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:2,
        explain:'Banana breaks into three syllable chunks: ba-na-na, with more than one syllable reducing to a schwa sound.'},
      {context:'granola', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:2,
        explain:'Granola breaks into three syllable chunks: gra-no-la.'},
      {context:'landscape', prompt:'Which letters form the welded chunk near the start?', options:['la','an','nd','ca'], answer:1,
        explain:'"An" is a welded sound taught early on — it stays glued together as one chunk wherever it appears, including inside landscape.'},
      {context:'splendid', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Splendid breaks into two syllable chunks: splen-did, both closed syllables.'},
      {context:'extra', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Extra breaks into two syllable chunks: ex-tra, both closed syllables.'},
    ]},
];

STORY_PACKS['grandma_day'] = {
  id: 'grandma_day',
  title: "A Day with Grandma",
  substep: '5.5AB',
  blurb: 'Two sisters make the long drive to visit Grandma — open syllable exceptions (schwa) in multisyllabic words.',
  type: 'controlled', // 'controlled' (WRS-decodable) or 'authentic' (real-world text)
  keyTerms: KEY_TERMS_GRANDMA_DAY,
  paragraphs: STORY_PARAGRAPHS_GRANDMA_DAY,
  rounds: ROUNDS_GRANDMA_DAY,
};
STORY_ORDER.push('grandma_day');
