/* ---------------------------------------------------------------
   STORY: Off to the Academy  (WRS Substep 5.5AB)
   Twin brothers prepare to leave home for a special academy — open syllable exceptions in multisyllabic words.
   Auto-split from the original single-file build — safe to hand-edit.
   To add a NEW story, copy this whole file, rename the three consts
   and the STORY_PACKS key/id, then add a <script src="stories/yourfile.js">
   line in index.html (order in that list = order in the case picker).
   Set type to 'authentic' for real-world (non-controlled) passages — this only
   changes the badge shown on the picker card, not how rounds are built.
--------------------------------------------------------------- */
const KEY_TERMS_OFF_TO_ACADEMY = ['soon','early','family','since','school','special','room'];

const STORY_PARAGRAPHS_OFF_TO_ACADEMY = [
  `Benny and Abraham are identical twin siblings who live in Alaska. Soon, they will be finishing school. In fact, they are ending classes early to begin a special program. In April, they will be attending an academy together where they will study politics. The academy is way on the other side of the state and miles from their family. The academy is beautiful, hidden among the Alaskan landscape of big sky and tall pines. The habitat is also rich with wildlife - bats, fish, foxes, and whales!`,
  `At the academy, Benny and Abraham will share a small and cozy room just like they do back home. Unlike at home, they will have to behave like adults and put up with all the strict rules.`,
  `Since they know they will get hungry and the menu at the academy does not look so good, Benny and Abraham plan to shop before they go. They plan to bring along packs of candy, jugs of coconut water, bagels, and boxes of jelly donuts. They will also get a sofa that can recline and blankets so their friends will have a spot to sit when they come to visit. Benny will take his instruments for music classes, and Abraham will take his baseball stuff.`,
  `Benny and Abraham are so happy to be sticking together at the academy. They are not just siblings, they are also the very best of friends!`,
];

const ROUNDS_OFF_TO_ACADEMY = [
  { id:'sequence', tab:'Timeline', title:"Case File 1 — Timeline Reconstruction", icon:'🗺️',
    intro:"Drag the evidence into the correct order to rebuild Benny and Abraham's plans.",
    type:'sequence', points:5,
    sets:[
      { label:'Getting ready to leave — put these in order', events:[
          "Benny and Abraham are finishing school early.",
          "They learn they'll attend a special academy in April.",
          "They find out the academy is far from their family.",
          "They learn they'll share a small, cozy room there.",
      ]},
      { label:'Shopping before they go — put these in order', events:[
          "They realize the academy menu doesn't look very good.",
          "They plan to buy candy, coconut water, bagels, and donuts.",
          "They plan to get a reclining sofa and blankets for visitors.",
          "Benny packs his instruments and Abraham packs his baseball stuff.",
      ]},
    ]},
  { id:'inference', tab:'Inference', title:"Case File 2 — Detective Inference", icon:'🧠',
    intro:"The best clues aren't always written in the text. Read between the lines to solve these.",
    type:'mc', points:12,
    questions:[
      {context:`"In fact, they are ending classes early to begin a special program."`, prompt:'What does "in fact" signal in this sentence?', 
        options:['A correction of what was just said','An emphasis that adds more specific detail to the previous statement','The end of the story','A change of subject entirely'], answer:1,
        explain:'"In fact" is used to add a more specific, emphasized detail — here, explaining exactly why they\'re finishing school soon.'},
      {context:`"The academy is way on the other side of the state and miles from their family."`, prompt:'What does this tell you about the twins\' upcoming experience?', 
        options:['They will be very close to home','They will be far away from their family for a while','Their family is moving with them','The academy is within walking distance'], answer:1,
        explain:'"Way on the other side of the state" and "miles from their family" both emphasize real physical distance from home.'},
      {context:`"Unlike at home, they will have to behave like adults and put up with all the strict rules."`, prompt:'What does this suggest about home versus the academy?', 
        options:['Home also has strict rules','The academy has stricter expectations than what they\'re used to at home','The academy has no rules at all','Home was stricter than the academy'], answer:1,
        explain:'"Unlike at home" signals a contrast — the academy demands more mature behavior and stricter rules than they experience at home.'},
      {context:`"Since they know they will get hungry and the menu at the academy does not look so good, Benny and Abraham plan to shop before they go."`, prompt:'Why are they doing extra shopping before leaving?', 
        options:['They think the academy food might not satisfy them','They enjoy shopping as a hobby','They were told to buy gifts','They are moving permanently'], answer:0,
        explain:'The sentence gives the reason directly — the unappealing menu is what\'s prompting them to stock up on snacks beforehand.'},
      {context:`"They will also get a sofa that can recline and blankets so their friends will have a spot to sit when they come to visit."`, prompt:'What does this tell you about the twins\' plans for their new room?', 
        options:['They don\'t expect any visitors','They are preparing to host friends comfortably in their room','They plan to sleep on the floor','They are avoiding making friends'], answer:1,
        explain:'Getting a reclining sofa and blankets specifically for visiting friends shows they\'re planning ahead to make their room welcoming.'},
      {context:`"Benny will take his instruments for music classes, and Abraham will take his baseball stuff."`, prompt:'What does this tell you about the twins\' individual interests?', 
        options:['They share the exact same hobbies','Despite being identical twins, they have some different personal interests','Neither twin has any hobbies','They will not be allowed hobbies at the academy'], answer:1,
        explain:'Benny brings music instruments while Abraham brings baseball gear — even as identical twins, they have distinct individual interests.'},
      {context:`"Benny and Abraham are so happy to be sticking together at the academy."`, prompt:'What does this line reveal about a source of comfort for the twins?', 
        options:['They are anxious about being separated','Being together eases any worry about the big change ahead','They wish they were going to different academies','They don\'t care whether they\'re together or not'], answer:1,
        explain:'Being "happy to be sticking together" suggests that facing this big change side-by-side, rather than alone, brings them comfort.'},
      {context:`"They are not just siblings, they are also the very best of friends!"`, prompt:'What is this final line emphasizing about their relationship?', 
        options:['They barely know each other','Their bond goes beyond just being related — they are close friends too','They often argue as siblings do','They are only connected through school'], answer:1,
        explain:'"Not just siblings, but also...best of friends" emphasizes that their relationship is deeper than family obligation — it\'s real friendship.'},
      {context:'Think about the whole story.', prompt:'What is one theme this story explores?', 
        options:['Facing a big life change is easier with someone you\'re close to by your side','Twins always dislike being compared to each other','New experiences are always disappointing','Family separation is never difficult'], answer:0,
        explain:'The twins face a big transition — leaving home, strict rules, an uncertain menu — but their closeness and being together seems to make it feel manageable and even exciting.'},
    ]},
  { id:'vocab', tab:'Vocab', title:"Case File 3 — Vocabulary Clues", icon:'🔍',
    intro:"Every good detective reads for clues hidden in context. Figure out what each word means the way it's used in the story.",
    type:'mc', points:10,
    questions:[
      {context:`"Benny and Abraham are identical twin siblings."`, prompt:'What does identical mean here?', 
        options:['Completely different from each other','Exactly alike in appearance','Older and younger','Living in separate homes'], answer:1,
        explain:'Identical means exactly alike — a common description for twins who look the same.'},
      {context:`"The academy is beautiful, hidden among the Alaskan landscape of big sky and tall pines."`, prompt:'What does hidden mean here?', 
        options:['Easy to find and very visible','Tucked away and not easily seen','Loud and obvious','Brightly lit'], answer:1,
        explain:'Hidden describes something tucked away, not easily seen — here, the academy nestled within the landscape.'},
      {context:`"The habitat is also rich with wildlife."`, prompt:'What does habitat mean here?', 
        options:['A type of building','The natural environment where animals live','A school subject','A kind of weather'], answer:1,
        explain:'A habitat is the natural environment where animals live — here, describing the area around the academy.'},
      {context:`"They will share a small and cozy room just like they do back home."`, prompt:'What does cozy mean here?', 
        options:['Cold and uncomfortable','Warm, comfortable, and snug','Large and empty','Loud and busy'], answer:1,
        explain:'Cozy describes a warm, comfortable, snug space — a positive description of their small shared room.'},
      {context:`"They will have to behave like adults and put up with all the strict rules."`, prompt:'What does strict mean here?', 
        options:['Loose and flexible','Firmly enforced, with little flexibility','Fun and relaxed','Optional'], answer:1,
        explain:'Strict describes rules that are firmly enforced with little flexibility — a contrast to how they\'re used to living at home.'},
      {context:`"They will also get a sofa that can recline."`, prompt:'What does recline mean here?', 
        options:['Fold up completely flat for storage','Tilt back into a more relaxed, laid-back position','Break apart','Become smaller'], answer:1,
        explain:'Recline describes tilting back into a relaxed position — a feature of comfortable furniture like a reclining sofa.'},
      {context:`"They will also get a sofa that can recline and blankets so their friends will have a spot to sit when they come to visit."`, prompt:'What does spot mean here?', 
        options:['A stain','A place or location','A type of animal','A game'], answer:1,
        explain:'Spot here means a place or location — specifically, a place for friends to sit when visiting.'},
      {context:`"Benny and Abraham are so happy to be sticking together at the academy."`, prompt:'What does sticking together mean here?', 
        options:['Being glued to an object','Staying close and remaining with each other','Fighting with each other','Ignoring one another'], answer:1,
        explain:'"Sticking together" means staying close and remaining with someone — here, the twins staying with each other at the academy.'},
      {context:`"In fact, they are ending classes early to begin a special program."`, prompt:'What does special mean here?', 
        options:['Ordinary and common','Distinct and set apart from the usual','Boring','Optional and easy to skip'], answer:1,
        explain:'Special describes something distinct or set apart from the ordinary — here, a notable program worth ending classes early for.'},
      {context:`"In April, they will be attending an academy together."`, prompt:'What does academy mean here?', 
        options:['A type of vacation','A school, especially one focused on a specific area of study','A sports team','A type of food'], answer:1,
        explain:'An academy is a school, often one focused on a particular subject — here, one focused on politics.'},
    ]},
  { id:'spelling', tab:'Spelling', title:"Case File 4 — Spelling Forensics", icon:'✏️',
    intro:"A detective's notes have to be exact. Listen to each word and spell it correctly to file it as evidence.",
    type:'spell', points:15,
    questions:[
      {word:'identical', sentence:'Benny and Abraham are identical twins.'},
      {word:'siblings', sentence:'They are twin siblings.'},
      {word:'academy', sentence:'They will attend a special academy.'},
      {word:'habitat', sentence:'The habitat is rich with wildlife.'},
      {word:'cozy', sentence:'Their room is small and cozy.'},
      {word:'recline', sentence:'The sofa they want can recline.'},
      {word:'coconut', sentence:'They plan to buy coconut water.'},
      {word:'bagels', sentence:'They will bring along bagels.'},
      {word:'program', sentence:'It is a special program.'},
      {word:'menu', sentence:'The menu does not look so good.'},
    ]},
  { id:'structure', tab:'Structure', title:"Case File 5 — Structure Analysis", icon:'🧩',
    intro:"This story features the open syllable exception, along with open, closed, and VCE syllables. Mark the sound chunks to crack the code.",
    type:'mc', points:10,
    questions:[
      {context:'identical', prompt:'How many syllables does this word have?', options:['2','3','4','5'], answer:2,
        explain:'Identical breaks into four syllable chunks: i-den-ti-cal.'},
      {context:'siblings', prompt:'Which letters form the welded chunk?', options:['si','bl','ing','ngs'], answer:2,
        explain:'"Ing" is a welded sound taught as one unit — it stays glued together wherever it appears, including inside siblings.'},
      {context:'academy', prompt:'The first syllable, "a," makes the schwa sound rather than its expected long sound. What is this pattern called?', options:['A closed syllable','An open syllable exception','A welded sound','A digraph'], answer:1,
        explain:'When an open syllable makes the schwa /ə/ sound instead of its expected long vowel sound, that\'s an open syllable exception — the focus pattern of this substep.'},
      {context:'habitat', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:2,
        explain:'Habitat breaks into three syllable chunks: hab-i-tat.'},
      {context:'cozy', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Cozy breaks into two syllable chunks: co-zy, both open syllables.'},
      {context:'recline', prompt:'What syllable type is the second syllable, "cline"?', options:['Open syllable','VCE (vowel-consonant-e)','Closed syllable','Welded'], answer:1,
        explain:'"Cline" has a vowel, then a consonant, then a silent e — that pattern is a VCE syllable, giving the i its long sound.'},
      {context:'coconut', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:2,
        explain:'Coconut breaks into three syllable chunks: co-co-nut.'},
      {context:'bagels', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Bagels breaks into two syllable chunks: ba-gels.'},
      {context:'program', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Program breaks into two syllable chunks: pro-gram, an open syllable followed by a closed syllable.'},
      {context:'menu', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Menu breaks into two syllable chunks: me-nu, both open syllables.'},
    ]},
];

STORY_PACKS['off_to_academy'] = {
  id: 'off_to_academy',
  title: "Off to the Academy",
  substep: '5.5AB',
  blurb: 'Twin brothers prepare to leave home for a special academy — open syllable exceptions in multisyllabic words.',
  type: 'controlled', // 'controlled' (WRS-decodable) or 'authentic' (real-world text)
  keyTerms: KEY_TERMS_OFF_TO_ACADEMY,
  paragraphs: STORY_PARAGRAPHS_OFF_TO_ACADEMY,
  rounds: ROUNDS_OFF_TO_ACADEMY,
};
STORY_ORDER.push('off_to_academy');
