/* ---------------------------------------------------------------
   STORY: Passing a Bill  (WRS Substep 3.5B)
   How a bill becomes a law, step by step — adding -ing to basewords.
   Auto-split from the original single-file build — safe to hand-edit.
   To add a NEW story, copy this whole file, rename the three consts
   and the STORY_PACKS key/id, then add a <script src="stories/yourfile.js">
   line in index.html (order in that list = order in the case picker).
   Set type to 'authentic' for real-world (non-controlled) passages — this only
   changes the badge shown on the picker card, not how rounds are built.
--------------------------------------------------------------- */
const KEY_TERMS_PASSING_BILL = ['often','throughout','called','great','through','starts','time','see','vote'];

const STORY_PARAGRAPHS_PASSING_BILL = [
  `Passing a bill in Congress is very complex. There are a number of steps, and every aspect of a bill is inspected. Hundreds of people work to help with the passing of just one bill.`,
  `Congress starts by collecting all the facts and then editing the text. They spend a lot of time checking the cost and discussing what is intended with each new bill. Often, the talk can go on throughout many months. Then, it is put into a transcript, publishing it for the press and the public to see.`,
  `At long last, a bill can be called up for a vote. Everyone in Congress can now cast their ballot. If most of them think it is great and say yes, then the bill will pass through.`,
];

const ROUNDS_PASSING_BILL = [
  { id:'sequence', tab:'Timeline', title:"Case File 1 — Timeline Reconstruction", icon:'🗺️',
    intro:"Drag the evidence into the correct order to rebuild how a bill passes.",
    type:'sequence', points:5,
    sets:[
      { label:'First half — put these in order', events:[
          "Congress starts by collecting all the facts about a bill.",
          "Congress spends time editing the text and checking the cost.",
          "Congress discusses what each new bill is intended to do.",
          "Talk about a bill can go on for months before it's finished.",
      ]},
      { label:'Second half — put these in order', events:[
          "The bill is put into a transcript for the press and public to see.",
          "A bill can be called up for a vote.",
          "Everyone in Congress casts their ballot.",
          "If most vote yes, the bill passes through.",
      ]},
    ]},
  { id:'inference', tab:'Inference', title:"Case File 2 — Detective Inference", icon:'🧠',
    intro:"Read between the lines to solve these.",
    type:'mc', points:12,
    questions:[
      {context:`"Passing a bill in Congress is very complex."`, prompt:'Why does the story say this at the start?',
        options:['To prepare the reader for the many detailed steps described afterward','To say passing a bill is easy','To describe a different topic','To confuse the reader'], answer:0,
        explain:'Calling the process "very complex" sets up the reader for the detailed multi-step process described next.'},
      {context:`"Hundreds of people work to help with the passing of just one bill."`, prompt:'What does this suggest about the process?',
        options:['It takes a huge collaborative effort, not just a few people','Only one person is needed','The process is quick','Most people are not involved'], answer:0,
        explain:'"Hundreds of people" for "just one bill" emphasizes how much collaboration is required.'},
      {context:`"every aspect of a bill is inspected"`, prompt:'Why is every aspect of a bill inspected?',
        options:['To make sure the bill is carefully checked before it becomes a law','Because inspections are required for fun','To slow down the process on purpose','Because bills are usually wrong'], answer:0,
        explain:'Careful inspection ensures the bill is correct and ready before it can become law.'},
      {context:`"the talk can go on throughout many months"`, prompt:'What can you infer from this line?',
        options:['Reaching agreement on a bill can take a very long time','Bills are decided in one day','Talking about a bill is unnecessary','Every bill takes exactly one month'], answer:0,
        explain:'"Many months" of ongoing talk shows this process can take a long time to complete.'},
      {context:`"it is put into a transcript, publishing it for the press and the public to see"`, prompt:'Why is the bill published for the public to see?',
        options:['So that the press and citizens have access to what\'s being proposed and discussed','To keep it secret from most people','Because it\'s required by tradition only','To confuse readers'], answer:0,
        explain:'Publishing the transcript makes the process transparent to the press and public.'},
      {context:`"At long last, a bill can be called up for a vote."`, prompt:'What does this suggest about the earlier steps?',
        options:['The discussion and editing steps must be finished before voting can happen','Voting happens before any discussion','The vote happens randomly','Anyone can vote at any time'], answer:0,
        explain:'"At long last" signals the vote is the final step, coming only after all the earlier work is done.'},
      {context:`"If most of them think it is great and say yes"`, prompt:'Why does the outcome depend on "most of them" rather than everyone?',
        options:['A bill doesn\'t need unanimous support, just a majority to pass','Every single member must agree','Only the boss decides','No votes are actually counted'], answer:0,
        explain:'"Most of them" indicates a majority vote is needed, not agreement from every single member.'},
      {context:`"Everyone in Congress can now cast their ballot."`, prompt:'What can you infer about the purpose of a ballot from this line?',
        options:['It\'s the formal way each member\'s decision is officially counted','It\'s just a suggestion box','It has no real effect','It\'s only symbolic'], answer:0,
        explain:'Casting a ballot is how each member\'s vote is formally recorded and counted toward the outcome.'},
      {context:'Think about the whole story.', prompt:'What is the theme of this story?',
        options:['Passing a law is a long, careful, and collaborative process','Laws are passed instantly','Only one person decides on laws','Voting doesn\'t matter'], answer:0,
        explain:'From collecting facts to the final vote, the story emphasizes how careful and collaborative this process is.'},
      {context:'The story ends right at the vote.', prompt:'Why might the author end the story right at the vote rather than describing what happens after a bill passes?',
        options:['To focus specifically on explaining the passing process itself, which was the story\'s purpose','Because nothing else happens after a vote','Because the author ran out of ideas','To confuse the reader'], answer:0,
        explain:'The story\'s purpose was explaining how a bill passes, so ending right at the vote completes that explanation.'},
    ]},
  { id:'vocab', tab:'Vocab', title:"Case File 3 — Vocabulary Clues", icon:'🔍',
    intro:"Every good detective reads for clues hidden in context. Figure out what each word means the way it's used in the story.",
    type:'mc', points:10,
    questions:[
      {context:`"Passing a bill in Congress is very complex."`, prompt:'What does complex mean here?',
        options:['Complicated, having many parts','Simple','Quick','Boring'], answer:0,
        explain:'Complex describes something with many parts — fitting the many steps described in passing a bill.'},
      {context:`"every aspect of a bill is inspected"`, prompt:'What does aspect mean here?',
        options:['A particular part or feature of something','The whole thing at once','A mistake','A summary'], answer:0,
        explain:'An aspect is one particular part of something — every part of the bill gets checked.'},
      {context:`"every aspect of a bill is inspected"`, prompt:'What does inspected mean here?',
        options:['Carefully examined or checked','Ignored','Guessed at','Thrown away'], answer:0,
        explain:'Inspecting something means carefully examining it, which happens to every part of a bill.'},
      {context:`"discussing what is intended with each new bill"`, prompt:'What does intended mean here?',
        options:['Meant or planned to happen','Accidental','Forgotten','Cancelled'], answer:0,
        explain:'Intended describes what is meant or planned — here, what the bill is supposed to accomplish.'},
      {context:`"it is put into a transcript"`, prompt:'What does transcript mean here?',
        options:['A written record of something, like spoken words','A spoken speech only','A drawing','A type of vote'], answer:0,
        explain:'A transcript is a written record, here of the discussions and facts about the bill.'},
      {context:`"Everyone in Congress can now cast their ballot."`, prompt:'What does ballot mean here?',
        options:['A formal vote, often on paper','A written speech','A type of law','A meeting'], answer:0,
        explain:'A ballot is a formal vote — how each Congress member records their decision.'},
      {context:`"cast their ballot"`, prompt:'What does cast mean here?',
        options:['To formally submit a vote','To write a bill','To read a bill','To cancel a vote'], answer:0,
        explain:'To cast a ballot means to formally submit your vote.'},
      {context:`"the talk can go on throughout many months"`, prompt:'What does throughout mean here?',
        options:['During the entire length of a period of time','Only at the very start','Only at the very end','Never'], answer:0,
        explain:'Throughout means during the entire span of time — here, many months of ongoing discussion.'},
      {context:`"checking the cost and discussing what is intended"`, prompt:'What does discussing mean here?',
        options:['Talking about something in detail to reach understanding','Ignoring completely','Arguing angrily only','Voting immediately'], answer:0,
        explain:'Discussing means talking through something carefully — here, what each bill is meant to do.'},
      {context:`"publishing it for the press and the public to see"`, prompt:'What does publishing mean here?',
        options:['Making information available for others to read','Hiding information','Deleting information','Keeping something secret'], answer:0,
        explain:'Publishing means making something available for others to read — here, the bill\'s transcript.'},
    ]},
  { id:'spelling', tab:'Spelling', title:"Case File 4 — Spelling Forensics", icon:'✏️',
    intro:"A detective's notes have to be exact. Listen to each word and spell it correctly to file it as evidence.",
    type:'spell', points:15,
    questions:[
      {word:'collecting', sentence:'Congress starts by collecting all the facts.'},
      {word:'editing', sentence:'They spend time editing the text.'},
      {word:'checking', sentence:'They spend time checking the cost.'},
      {word:'discussing', sentence:'They spend time discussing what is intended.'},
      {word:'publishing', sentence:'It is put into a transcript, publishing it for the public.'},
      {word:'passing', sentence:'Passing a bill in Congress is complex.'},
      {word:'inspected', sentence:'Every aspect of a bill is inspected.'},
      {word:'intended', sentence:'They discuss what is intended with each bill.'},
      {word:'transcript', sentence:'It is put into a transcript.'},
      {word:'ballot', sentence:'Everyone can cast their ballot.'},
    ]},
  { id:'structure', tab:'Structure', title:"Case File 5 — Structure Analysis", icon:'🧩',
    intro:"This story adds -ing to basewords. Mark the welded ing chunks and digraphs to crack the code.",
    type:'mc', points:10,
    questions:[
      {context:'collecting', prompt:'Which letters form the welded chunk at the end?', options:['co','ll','ct','ing'], answer:3,
        explain:'"Ing" is a welded sound taught as one unit — it gets added onto the baseword "collect."'},
      {context:'editing', prompt:'Which letters form the welded chunk at the end?', options:['ed','it','ti','ing'], answer:3,
        explain:'"Ing" is a welded sound taught as one unit — it gets added onto the baseword "edit."'},
      {context:'checking', prompt:'Which letters form the beginning digraph?', options:['ch','ec','ki','ng'], answer:0,
        explain:'C and h together make one new sound, /ch/, at the start of checking.'},
      {context:'checking', prompt:'Which letters form the digraph before the ending?', options:['ch','ec','ck','ing'], answer:2,
        explain:'C and k together make one new sound, /ck/, right before the -ing ending.'},
      {context:'publishing', prompt:'Which letters form the digraph?', options:['pu','bl','sh','ing'], answer:2,
        explain:'S and h together make one new sound, /sh/, in publishing.'},
      {context:'transcript', prompt:'Which letters form the welded chunk in this word?', options:['tr','an','sc','ip'], answer:1,
        explain:'"An" is a welded sound taught as one unit — you can hear it stay together in transcript.'},
      {context:'ballot', prompt:'Which letters form the welded chunk in this word?', options:['ba','all','ot','lo'], answer:1,
        explain:'"All" is a welded sound taught as one unit — you can hear it stay together in ballot.'},
      {context:'discussing', prompt:'How many syllables does this word have?', options:['2','3','4','5'], answer:1,
        explain:'Discussing breaks into three syllable chunks: dis-cuss-ing.'},
      {context:'inspected', prompt:'How many syllables does this word have?', options:['2','3','4','5'], answer:1,
        explain:'Inspected breaks into three syllable chunks: in-spect-ed.'},
      {context:'intended', prompt:'How many syllables does this word have?', options:['2','3','4','5'], answer:1,
        explain:'Intended breaks into three syllable chunks: in-tend-ed.'},
    ]},
];

STORY_PACKS['passing_a_bill'] = {
  id: 'passing_a_bill',
  title: "Passing a Bill",
  substep: '3.5B',
  blurb: 'How a bill becomes a law, step by step — adding -ing to basewords.',
  type: 'controlled', // 'controlled' (WRS-decodable) or 'authentic' (real-world text)
  keyTerms: KEY_TERMS_PASSING_BILL,
  paragraphs: STORY_PARAGRAPHS_PASSING_BILL,
  rounds: ROUNDS_PASSING_BILL,
};
STORY_ORDER.push('passing_a_bill');
