/* ---------------------------------------------------------------
   STORY: The Pony Ride  (WRS Substep 5.3AB)
   A first pony ride turns a shy start into a happy afternoon — open syllables, VCE, and closed syllables.
   Auto-split from the original single-file build — safe to hand-edit.
   To add a NEW story, copy this whole file, rename the three consts
   and the STORY_PACKS key/id, then add a <script src="stories/yourfile.js">
   line in index.html (order in that list = order in the case picker).
   Set type to 'authentic' for real-world (non-controlled) passages — this only
   changes the badge shown on the picker card, not how rounds are built.
--------------------------------------------------------------- */
const KEY_TERMS_PONY_RIDE = ['don\'t','beautiful','woman','pretty','person','whose'];

const STORY_PARAGRAPHS_PONY_RIDE = [
  `Sally is five years old, and she has always wanted to go on a pony ride. She has made this request many times. At last, her dad comes into the house and asks, "Sally, don't you think we ought to go on that pony ride today? Let's go now!"`,
  `Dad, Mom, and Sally drive twelve miles until they find the big ranch owned by Mrs. Holly. The land is wide, and there is a tall windmill just past the chicken shed.`,
  `The three walk over to the pen to stare at the beautiful pony. However, Sally does not get too close. She hides behind her dad and acts in a shy way. It takes her some time to learn that it is safe to be next to the tiny pony whose name is Benny.`,
  `When the woman swings the gate open, Sally gives Benny a big hug and small pat on his mane. After a quick lesson to prepare, Sally gets on the pony and yells, "He is so pretty!" Sally looks around the ranch and spots rabbits, ducks, hens, and a jumbo pig. She is a very happy person on top of this strong pony.`,
  `When it is time to go, Sally thanks the ranch lady, Mrs. Holly, and hopes to come back to ride Benny again.`,
];

const ROUNDS_PONY_RIDE = [
  { id:'sequence', tab:'Timeline', title:"Case File 1 — Timeline Reconstruction", icon:'🗺️',
    intro:"Drag the evidence into the correct order to rebuild Sally's day at the ranch.",
    type:'sequence', points:5,
    sets:[
      { label:'Getting to the ranch — put these in order', events:[
          "Sally asks for a pony ride many times.",
          "Dad finally says it's time to go.",
          "The family drives twelve miles to the ranch.",
          "They spot the windmill past the chicken shed.",
      ]},
      { label:'Meeting Benny — put these in order', events:[
          "Sally hides behind her dad, feeling shy.",
          "Sally learns it's safe to stand next to Benny.",
          "The woman swings the gate open and Sally hugs Benny.",
          "Sally rides Benny and spots the other animals on the ranch.",
      ]},
    ]},
  { id:'inference', tab:'Inference', title:"Case File 2 — Detective Inference", icon:'🧠',
    intro:"The best clues aren't always written in the text. Read between the lines to solve these.",
    type:'mc', points:12,
    questions:[
      {context:`"She has made this request many times."`, prompt:'What does this tell you about how long Sally has wanted this?', 
        options:['She just thought of it today','She has wanted a pony ride for a while','She changed her mind often','She doesn\'t really want to go'], answer:1,
        explain:'"Many times" signals this isn\'t a new wish — Sally has been asking repeatedly, which means she\'s wanted this for a while.'},
      {context:`"Sally, don't you think we ought to go on that pony ride today? Let's go now!"`, prompt:'What can you infer about Dad\'s mood here?', 
        options:['He is annoyed by Sally\'s requests','He is excited to finally take her','He forgot about the pony ride','He is unsure if they should go'], answer:1,
        explain:'"Let\'s go now!" is an enthusiastic, immediate call to action — the tone suggests excitement, not reluctance or forgetfulness.'},
      {context:`"However, Sally does not get too close. She hides behind her dad and acts in a shy way."`, prompt:'What does this tell you about Sally\'s first reaction to the pony?', 
        options:['She was fearless from the start','She felt nervous meeting the pony','She didn\'t want a pony ride at all','She was bored'], answer:1,
        explain:'Hiding behind her dad right when she gets close to the pony is a clear sign of shyness or nervousness, not fearlessness.'},
      {context:`"It takes her some time to learn that it is safe to be next to the tiny pony."`, prompt:'What does "takes her some time" suggest?', 
        options:['Sally warmed up to Benny gradually','Sally never got comfortable','Sally left right away','Sally rode Benny immediately'], answer:0,
        explain:'"Takes some time" describes a gradual process — Sally didn\'t trust Benny instantly, but she did get there eventually.'},
      {context:`"Sally gives Benny a big hug and small pat on his mane."`, prompt:'What does this action show about how Sally feels now, compared to earlier?', 
        options:['She is still afraid of Benny','She has become comfortable and affectionate with Benny','She wants to leave','She is ignoring Benny'], answer:1,
        explain:'Hugging and patting Benny is affectionate, physical closeness — a big shift from hiding behind her dad just a bit earlier.'},
      {context:`"Sally gets on the pony and yells, 'He is so pretty!'"`, prompt:'What does yelling this line tell you about Sally\'s mood?', 
        options:['She is scared','She is thrilled and excited','She is disappointed','She is calm and quiet'], answer:1,
        explain:'Yelling an excited compliment while riding shows Sally is thrilled — a big change from the shy girl hiding earlier in the story.'},
      {context:`"She is a very happy person on top of this strong pony."`, prompt:'What is the story telling you directly here?', 
        options:['Sally regrets coming','Sally is enjoying the ride','Sally is scared of falling','Sally wants to go home'], answer:1,
        explain:'This line states Sally\'s happiness plainly — a direct statement of how she feels at this point in the ride.'},
      {context:`"She hopes to come back to ride Benny again."`, prompt:'What does this ending tell you about Sally\'s experience overall?', 
        options:['She had a bad time and won\'t return','She had a great time and wants to repeat it','She is indifferent about ponies now','She is scared to ever ride again'], answer:1,
        explain:'Wanting to "come back" and ride "again" only makes sense if the experience was a positive one she wants to repeat.'},
      {context:'Think about the whole story.', prompt:'What is one theme this story explores?', 
        options:['New experiences can feel scary at first but become enjoyable','Animals are always dangerous','You should never try new things','Family trips are always boring'], answer:0,
        explain:'Sally starts out shy and hesitant around Benny, then ends the story happy and wanting to return — that arc is the clue to the theme.'},
    ]},
  { id:'vocab', tab:'Vocab', title:"Case File 3 — Vocabulary Clues", icon:'🔍',
    intro:"Every good detective reads for clues hidden in context. Figure out what each word means the way it's used in the story.",
    type:'mc', points:10,
    questions:[
      {context:`"She has made this request many times."`, prompt:'What does request mean here?', 
        options:['A gift','An ask for something wanted','A complaint','A rule'], answer:1,
        explain:'A request is an ask for something — here, Sally repeatedly asking to go on a pony ride.'},
      {context:`"Sally, don't you think we ought to go on that pony ride today?"`, prompt:'What does ought to mean here?', 
        options:['Should','Might not','Refuse to','Forgot to'], answer:0,
        explain:'"Ought to" means "should" — Dad is suggesting they should go, not questioning whether to.'},
      {context:`"There is a tall windmill just past the chicken shed."`, prompt:'What does shed mean here?', 
        options:['A tall tower','A small, simple building for storage or animals','A type of pony','A fence'], answer:1,
        explain:'A shed is a small structure — here, one near the chicken area of the ranch, separate from the windmill.'},
      {context:`"The three walk over to the pen to stare at the beautiful pony."`, prompt:'What does pen mean here?', 
        options:['A writing tool','An enclosed area for animals','A type of saddle','A barn door'], answer:1,
        explain:'A pen is a fenced or enclosed space for keeping animals — that\'s where the pony is kept for the family to see.'},
      {context:`"She hides behind her dad and acts in a shy way."`, prompt:'What does shy mean here?', 
        options:['Loud and bold','Nervous and hesitant around new things','Angry','Very tired'], answer:1,
        explain:'Acting "shy" and hiding behind her dad both point to Sally feeling nervous or hesitant, not bold.'},
      {context:`"After a quick lesson to prepare, Sally gets on the pony."`, prompt:'What does prepare mean here?', 
        options:['To get ready for something','To finish something','To forget something','To ride quickly'], answer:0,
        explain:'A "lesson to prepare" is instruction that gets Sally ready before she actually gets on the pony.'},
      {context:`"Sally looks around the ranch and spots rabbits, ducks, hens, and a jumbo pig."`, prompt:'What does jumbo mean here?', 
        options:['Tiny','Very large','Fast','Colorful'], answer:1,
        explain:'Jumbo describes something very large — here, describing an especially big pig on the ranch.'},
      {context:`"It is safe to be next to the tiny pony whose name is Benny."`, prompt:'What does tiny mean here?', 
        options:['Very small','Very loud','Very fast','Very old'], answer:0,
        explain:'Tiny means very small — it describes Benny\'s size, which is part of why Sally eventually feels safe near him.'},
      {context:`"When the woman swings the gate open."`, prompt:'What does swings mean here?', 
        options:['Throws something away','Moves something in an arc, like opening a gate','Hits something hard','Ties something shut'], answer:1,
        explain:'Swinging a gate open describes the arc-like motion of a gate moving on its hinge to open.'},
      {context:`"She has always wanted to go on a pony ride."`, prompt:'What does always mean here?', 
        options:['Never','For the whole time, without exception','Only once','Rarely'], answer:1,
        explain:'"Always" means the entire time — Sally has wanted this the whole time, not just recently.'},
    ]},
  { id:'spelling', tab:'Spelling', title:"Case File 4 — Spelling Forensics", icon:'✏️',
    intro:"A detective's notes have to be exact. Listen to each word and spell it correctly to file it as evidence.",
    type:'spell', points:15,
    questions:[
      {word:'request', sentence:'Sally made this request many times.'},
      {word:'windmill', sentence:'There is a tall windmill by the shed.'},
      {word:'prepare', sentence:'Sally had a lesson to prepare.'},
      {word:'jumbo', sentence:'She spots a jumbo pig.'},
      {word:'pony', sentence:'Sally rides the pony named Benny.'},
      {word:'tiny', sentence:'Benny is a tiny pony.'},
      {word:'chicken', sentence:'The windmill is past the chicken shed.'},
      {word:'mane', sentence:'Sally pats Benny on his mane.'},
      {word:'rabbit', sentence:'Sally spots a rabbit on the ranch.'},
      {word:'ranch', sentence:'The family visits the big ranch.'},
    ]},
  { id:'structure', tab:'Structure', title:"Case File 5 — Structure Analysis", icon:'🧩',
    intro:"This story mixes open syllables with VCE and closed syllables. Mark the sound chunks to crack the code.",
    type:'mc', points:10,
    questions:[
      {context:'request', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Request breaks into two syllable chunks: re-quest, an open syllable followed by a closed syllable.'},
      {context:'windmill', prompt:'Which letters form the welded chunk?', options:['wi','ind','mi','ll'], answer:1,
        explain:'"Ind" is a welded sound taught as one unit — it stays glued together wherever it shows up, including inside windmill.'},
      {context:'windmill', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Windmill breaks into two chunks: wind-mill, both closed syllables — it\'s a compound word made of two smaller words.'},
      {context:'prepare', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Prepare breaks into two syllable chunks: pre-pare, an open syllable followed by a VCE syllable.'},
      {context:'jumbo', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Jumbo breaks into two syllable chunks: jum-bo, a closed syllable followed by an open syllable.'},
      {context:'pony', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Pony breaks into two syllable chunks: po-ny, both open syllables.'},
      {context:'tiny', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Tiny breaks into two syllable chunks: ti-ny, both open syllables.'},
      {context:'chicken', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Chicken breaks into two syllable chunks: chick-en, both closed syllables.'},
      {context:'rabbit', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Rabbit breaks into two syllable chunks: rab-bit, both closed syllables.'},
      {context:'mane', prompt:'What syllable type is this word?', options:['Open syllable','VCE (vowel-consonant-e)','Closed syllable','Welded'], answer:1,
        explain:'Mane has a vowel, then a consonant, then a silent e — that pattern is a VCE syllable, giving the a its long sound.'},
    ]},
];

STORY_PACKS['pony_ride'] = {
  id: 'pony_ride',
  title: "The Pony Ride",
  substep: '5.3AB',
  blurb: 'A first pony ride turns a shy start into a happy afternoon — open syllables, VCE, and closed syllables.',
  type: 'controlled', // 'controlled' (WRS-decodable) or 'authentic' (real-world text)
  keyTerms: KEY_TERMS_PONY_RIDE,
  paragraphs: STORY_PARAGRAPHS_PONY_RIDE,
  rounds: ROUNDS_PONY_RIDE,
};
STORY_ORDER.push('pony_ride');
