/* ---------------------------------------------------------------
   STORY: Ruby, the Red Bulldog  (WRS Substep 5.3AB)
   A quirky, beloved bulldog and her daily routine — open syllables, VCE, closed syllables, and welded sounds.
   Auto-split from the original single-file build — safe to hand-edit.
   To add a NEW story, copy this whole file, rename the three consts
   and the STORY_PACKS key/id, then add a <script src="stories/yourfile.js">
   line in index.html (order in that list = order in the case picker).
   Set type to 'authentic' for real-world (non-controlled) passages — this only
   changes the badge shown on the picker card, not how rounds are built.
--------------------------------------------------------------- */
const KEY_TERMS_RUBY_BULLDOG = ['beautiful','pretty','person','woman','bulldog','above','ago','night'];

const STORY_PARAGRAPHS_RUBY_BULLDOG = [
  `Ruby is a wild and crazy dog. She has folds of skin above her nose and hanging from her neck. Ruby also has an underbite, but her owner, Peggy, thinks she is beautiful just the same. Ruby likes to lick Peggy's legs when she gets home from work. Then, the reddish dog is happy to take a quick nap and snore in her fluffy bed.`,
  `Peggy brought Ruby to her home two years ago when Ruby was just a puppy. She was a tiny thing then, but now Ruby is a pretty big dog. She likes to munch on her dog food until her belly is full. Before it's time to go to bed for the night, Peggy takes Ruby outside to go for a run in the grass. Peggy sits and flips through a small part of her book. This part of the day is fun for Ruby. She gets to chase a chipmunk or bunny until dusk.`,
  `Peggy thinks that Ruby sometimes acts more like a person than a dog. Ruby walks around the house with a strut in her step, then zips out onto the deck and jumps up on the hammock. This funny move makes Peggy smile every time! Life without Ruby would surely be a lonesome one, and Peggy thinks, "I would be a sad woman if Ruby was not here!"`,
];

const ROUNDS_RUBY_BULLDOG = [
  { id:'sequence', tab:'Timeline', title:"Case File 1 — Timeline Reconstruction", icon:'🗺️',
    intro:"Drag the evidence into the correct order to rebuild Ruby's typical day.",
    type:'sequence', points:5,
    sets:[
      { label:'Coming home from work — put these in order', events:[
          "Ruby licks Peggy's legs when she gets home.",
          "Ruby takes a quick nap and snores in her fluffy bed.",
          "Ruby munches on her dog food until her belly is full.",
          "Peggy takes Ruby outside for a run before bed.",
      ]},
      { label:'Evening playtime — put these in order', events:[
          "Peggy sits and reads part of her book.",
          "Ruby chases a chipmunk or bunny until dusk.",
          "Ruby struts around the house.",
          "Ruby zips onto the deck and jumps on the hammock.",
      ]},
    ]},
  { id:'inference', tab:'Inference', title:"Case File 2 — Detective Inference", icon:'🧠',
    intro:"The best clues aren't always written in the text. Read between the lines to solve these.",
    type:'mc', points:12,
    questions:[
      {context:`"Ruby also has an underbite, but her owner, Peggy, thinks she is beautiful just the same."`, prompt:'What does "just the same" tell you about Peggy\'s feelings?', 
        options:['Peggy doesn\'t like Ruby\'s looks','Peggy loves Ruby despite her unusual features','Peggy wants to change Ruby','Peggy is embarrassed by Ruby'], answer:1,
        explain:'"Just the same" means the underbite doesn\'t change Peggy\'s opinion — she still sees Ruby as beautiful regardless.'},
      {context:`"Then, the reddish dog is happy to take a quick nap and snore in her fluffy bed."`, prompt:'What does this tell you about Ruby after coming home?', 
        options:['She is anxious and can\'t settle down','She is relaxed and comfortable enough to sleep','She wants to go back outside','She is hungry and won\'t rest'], answer:1,
        explain:'Napping and snoring comfortably shows Ruby is relaxed and at ease in her own home.'},
      {context:`"She likes to munch on her dog food until her belly is full."`, prompt:'What does "until her belly is full" suggest about Ruby\'s eating habits?', 
        options:['She eats very little','She eats until she is satisfied','She never eats','She shares her food'], answer:1,
        explain:'Eating "until" her belly is full describes eating to the point of being satisfied, not stopping early or not eating at all.'},
      {context:`"This part of the day is fun for Ruby. She gets to chase a chipmunk or bunny until dusk."`, prompt:'What does this tell you about Ruby\'s personality?', 
        options:['She is lazy and prefers sleeping all day','She has a playful, energetic side','She is afraid of small animals','She dislikes being outside'], answer:1,
        explain:'Enjoying the chase of small animals until dusk shows an energetic, playful side to Ruby, beyond her earlier napping.'},
      {context:`"Ruby walks around the house with a strut in her step."`, prompt:'What does a "strut" suggest about how Ruby carries herself?', 
        options:['She walks confidently, almost proudly','She limps in pain','She crawls slowly','She hides from view'], answer:0,
        explain:'A strut is a confident, almost proud way of walking — it fits with Peggy later saying Ruby acts more like a person than a dog.'},
      {context:`"This funny move makes Peggy smile every time!"`, prompt:'What does "every time" tell you about how often this happens?', 
        options:['It happened just once','This is a regular occurrence that always amuses Peggy','It never happens anymore','Peggy is getting tired of it'], answer:1,
        explain:'"Every time" signals this is a repeated behavior that consistently makes Peggy smile, not a one-time event.'},
      {context:`"Life without Ruby would surely be a lonesome one."`, prompt:'What does this line reveal about how important Ruby is to Peggy?', 
        options:['Peggy could easily live without Ruby','Ruby fills an important, irreplaceable role in Peggy\'s life','Peggy is thinking of finding a new dog','Peggy rarely thinks about Ruby'], answer:1,
        explain:'Imagining life as "lonesome" without Ruby shows how much companionship and meaning Ruby brings to Peggy\'s life.'},
      {context:`"Peggy thinks that Ruby sometimes acts more like a person than a dog."`, prompt:'What kind of behaviors likely led Peggy to think this?', 
        options:['Ruby barks a lot','Ruby does human-like things, like strutting and jumping on the hammock','Ruby sleeps all day','Ruby never plays'], answer:1,
        explain:'The very next sentences describe Ruby strutting and using the hammock — human-like behaviors that support this observation.'},
      {context:'Think about the whole story.', prompt:'What is one theme this story explores?', 
        options:['Pets can become deeply loved members of a family','Dogs should not be kept as pets','Bulldogs are difficult to care for','Peggy regrets getting a dog'], answer:0,
        explain:'From her quirky looks to her human-like antics, the story paints Ruby as a beloved companion whose absence would leave Peggy lonesome — that bond is the theme.'},
    ]},
  { id:'vocab', tab:'Vocab', title:"Case File 3 — Vocabulary Clues", icon:'🔍',
    intro:"Every good detective reads for clues hidden in context. Figure out what each word means the way it's used in the story.",
    type:'mc', points:10,
    questions:[
      {context:`"She has folds of skin above her nose."`, prompt:'What does folds mean here?', 
        options:['Loose, bunched-up sections of skin','Sharp edges','Bright colors','Smooth, flat areas'], answer:0,
        explain:'Folds describes skin that bunches up rather than lying flat — a common bulldog feature.'},
      {context:`"Ruby also has an underbite."`, prompt:'What does underbite mean here?', 
        options:['A type of bark','A jaw where the lower teeth stick out past the upper teeth','A missing tooth','A type of collar'], answer:1,
        explain:'An underbite is a jaw shape where the bottom teeth extend past the top ones — a physical trait, like the folds of skin mentioned nearby.'},
      {context:`"The reddish dog is happy to take a quick nap and snore in her fluffy bed."`, prompt:'What does fluffy mean here?', 
        options:['Hard and stiff','Soft and puffy','Cold and damp','Loud and squeaky'], answer:1,
        explain:'Fluffy describes something soft and puffy — a cozy detail about the bed Ruby naps in.'},
      {context:`"She likes to munch on her dog food."`, prompt:'What does munch mean here?', 
        options:['To chew steadily','To sniff','To bark','To bury'], answer:0,
        explain:'Munch describes the act of chewing food, often steadily — that\'s what Ruby is doing with her dog food.'},
      {context:`"She gets to chase a chipmunk or bunny until dusk."`, prompt:'What does dusk mean here?', 
        options:['Early morning','The time just before nightfall','The middle of the day','Midnight'], answer:1,
        explain:'Dusk refers to the period right before it gets fully dark — the end of an outdoor evening chase.'},
      {context:`"Ruby walks around the house with a strut in her step."`, prompt:'What does strut mean here?', 
        options:['A confident, showy way of walking','A limping walk','A crawling motion','Standing completely still'], answer:0,
        explain:'A strut is a proud, confident style of walking — fitting with the idea that Ruby acts almost like a person.'},
      {context:`"Then zips out onto the deck."`, prompt:'What does zips mean here?', 
        options:['Moves very slowly','Moves quickly','Falls down','Stops completely'], answer:1,
        explain:'Zipping describes quick movement — Ruby dashing out onto the deck rather than moving slowly.'},
      {context:`"Life without Ruby would surely be a lonesome one."`, prompt:'What does lonesome mean here?', 
        options:['Exciting and full','Feeling alone and empty','Busy and crowded','Calm and peaceful'], answer:1,
        explain:'Lonesome describes a feeling of being alone — Peggy imagines life would feel empty without Ruby\'s company.'},
      {context:`"Before it's time to go to bed for the night, Peggy takes Ruby outside to go for a run."`, prompt:'What does run mean here?', 
        options:['A fast bit of exercise outdoors','A type of leash','A type of dog food','A nap'], answer:0,
        explain:'A "run" here is physical exercise outside — a walk or jog before bedtime, not an object or food.'},
      {context:`"Peggy sits and flips through a small part of her book."`, prompt:'What does flips through mean here?', 
        options:['Throws the book away','Pages through the book casually','Reads every word carefully','Writes in the book'], answer:1,
        explain:'"Flips through" describes casually turning pages rather than reading closely — a relaxed activity while Ruby plays nearby.'},
    ]},
  { id:'spelling', tab:'Spelling', title:"Case File 4 — Spelling Forensics", icon:'✏️',
    intro:"A detective's notes have to be exact. Listen to each word and spell it correctly to file it as evidence.",
    type:'spell', points:15,
    questions:[
      {word:'bulldog', sentence:'Ruby is a red bulldog.'},
      {word:'reddish', sentence:'The reddish dog takes a nap.'},
      {word:'fluffy', sentence:'Ruby sleeps in her fluffy bed.'},
      {word:'puppy', sentence:'Ruby was just a puppy two years ago.'},
      {word:'belly', sentence:'Ruby eats until her belly is full.'},
      {word:'chipmunk', sentence:'Ruby chases a chipmunk until dusk.'},
      {word:'hammock', sentence:'Ruby jumps up on the hammock.'},
      {word:'munch', sentence:'She likes to munch on her food.'},
      {word:'strut', sentence:'Ruby walks with a strut in her step.'},
      {word:'snore', sentence:'Ruby takes a quick nap and snores in her bed.'},
    ]},
  { id:'structure', tab:'Structure', title:"Case File 5 — Structure Analysis", icon:'🧩',
    intro:"This story mixes open syllables with VCE, closed syllables, and welded sounds. Mark the sound chunks to crack the code.",
    type:'mc', points:10,
    questions:[
      {context:'bulldog', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Bulldog breaks into two syllable chunks: bull-dog, a compound word made of two closed syllables.'},
      {context:'reddish', prompt:'Which letters form the ending digraph?', options:['re','dd','sh','di'], answer:2,
        explain:'S and h together make one new sound, /sh/, instead of two separate sounds — that fused sound is what makes sh a digraph.'},
      {context:'fluffy', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Fluffy breaks into two syllable chunks: fluf-fy, a closed syllable followed by an open syllable using y as a vowel.'},
      {context:'puppy', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Puppy breaks into two syllable chunks: pup-py, a closed syllable followed by an open syllable using y as a vowel.'},
      {context:'belly', prompt:'How many syllables does this word have?', options:['1','2','3','4'], answer:1,
        explain:'Belly breaks into two syllable chunks: bel-ly, a closed syllable followed by an open syllable using y as a vowel.'},
      {context:'chipmunk', prompt:'Which letters form the welded chunk?', options:['ch','ip','un','unk'], answer:3,
        explain:'"Unk" is a welded sound taught as one unit — you can hear it stay together at the end of chipmunk.'},
      {context:'hammock', prompt:'Which letters form the welded chunk?', options:['ha','am','mo','ck'], answer:1,
        explain:'"Am" is a welded sound taught early on — it stays glued together as one chunk wherever it appears, including inside hammock.'},
      {context:'munch', prompt:'Which letters form the ending digraph?', options:['mu','un','nc','ch'], answer:3,
        explain:'C and h together make one new sound, /ch/, instead of two separate sounds — that\'s what makes ch a digraph.'},
      {context:'strut', prompt:'How many sounds are in this word? (s / t / r / u / t)', options:['3','4','5','2'], answer:2,
        explain:'Strut has no digraphs, so every letter keeps its own sound: /s/ /t/ /r/ /u/ /t/ — 5 separate sounds.'},
      {context:'snore', prompt:'What syllable type is this word?', options:['Open syllable','VCE (vowel-consonant-e)','Closed syllable','Welded'], answer:1,
        explain:'Snore has a vowel, then a consonant, then a silent e — that VCE pattern is what\'s shaping the vowel sound here.'},
    ]},
];

STORY_PACKS['ruby_bulldog'] = {
  id: 'ruby_bulldog',
  title: "Ruby, the Red Bulldog",
  substep: '5.3AB',
  blurb: 'A quirky, beloved bulldog and her daily routine — open syllables, VCE, closed syllables, and welded sounds.',
  type: 'controlled', // 'controlled' (WRS-decodable) or 'authentic' (real-world text)
  keyTerms: KEY_TERMS_RUBY_BULLDOG,
  paragraphs: STORY_PARAGRAPHS_RUBY_BULLDOG,
  rounds: ROUNDS_RUBY_BULLDOG,
};
STORY_ORDER.push('ruby_bulldog');
