/* ---------------------------------------------------------------
   STORY: The Draft  (WRS Substep 2.4B)
   Waiting for the call that could change everything — closed syllables, blends, and welded sounds.
   Auto-split from the original single-file build — safe to hand-edit.
   To add a NEW story, copy this whole file, rename the three consts
   and the STORY_PACKS key/id, then add a <script src="stories/yourfile.js">
   line in index.html (order in that list = order in the case picker).
   Set type to 'authentic' for real-world (non-controlled) passages — this only
   changes the badge shown on the picker card, not how rounds are built.
--------------------------------------------------------------- */
const KEY_TERMS_THE_DRAFT = ['out','front','said','only','day','sure','team','came','phone','news'];

const STORY_PARAGRAPHS_THE_DRAFT = [
  `The day of the big draft was coming fast. Dell had been put at the top of the ranks at the try out. He was sure to be out in front for this draft. His runs were swift and his jumps were long. His lifts were the best as well. There was not anyone who could crush his stats. The team staff said that they did want a jock with his skills.`,
  `In the class of picks for the one spot on the team, Dell had big wishes that he would get the call. Yet, he was putting this all out of his mind for now. It was all up to the team staff. There was not anything he could do but be on hold.`,
  `Then the call came and Dell had to lift his phone quick when it rang to check if it was a prank. It was not! The call was not just from anyone. It was from the team and they did pick him and only him. Dell had to grasp the news fast. Then he ran off to tell his mom, dad, and all his pals.`,
];

const ROUNDS_THE_DRAFT = [
  { id:'sequence', tab:'Timeline', title:"Case File 1 — Timeline Reconstruction", icon:'🗺️',
    intro:"Drag the evidence into the correct order to rebuild Dell's draft day.",
    type:'sequence', points:5,
    sets:[
      { label:'Before the call — put these in order', events:[
          "Dell was put at the top of the ranks at the try out.",
          "The team staff said they wanted a jock with his skills.",
          "Dell had big wishes that he would get the call.",
          "Dell put the thought out of his mind and waited on hold.",
      ]},
      { label:'The call — put these in order', events:[
          "The phone rang and Dell lifted it quickly.",
          "Dell checked to see if the call was a prank.",
          "Dell found out the team picked him and only him.",
          "Dell ran off to tell his mom, dad, and his pals.",
      ]},
    ]},
  { id:'inference', tab:'Inference', title:"Case File 2 — Detective Inference", icon:'🧠',
    intro:"The best clues aren't always written in the text. Read between the lines to solve these.",
    type:'mc', points:12,
    questions:[
      {context:`"Dell had been put at the top of the ranks at the try out."`, prompt:'What does this tell you about Dell\'s try out?', 
        options:['He did poorly','He performed better than everyone else','He did not try out','He tied with another player'], answer:1,
        explain:'Being "at the top of the ranks" means Dell outperformed the other players trying out — that\'s the clue.'},
      {context:`"His runs were swift and his jumps were long. His lifts were the best as well."`, prompt:'What can you infer about Dell as an athlete?', 
        options:['He is only good at one skill','He is strong across multiple skills','He is average at everything','He struggles with jumping'], answer:1,
        explain:'The text lists three separate strengths — running, jumping, and lifting — showing Dell excels in more than just one area.'},
      {context:`"There was not anyone who could crush his stats."`, prompt:'What does this line suggest about the competition?', 
        options:['No one else was competitive with Dell\'s numbers','Everyone had better stats than Dell','The stats were not tracked','Dell had the worst stats'], answer:0,
        explain:'"Not anyone who could crush his stats" means nobody could beat his numbers — Dell was ahead of the field.'},
      {context:`"Yet, he was putting this all out of his mind for now."`, prompt:'Why might Dell try not to think about the draft?', 
        options:['He didn\'t care about the outcome','Thinking about it constantly might make the wait harder','He forgot about the try out','He already knew the answer'], answer:1,
        explain:'Right before this, Dell "had big wishes" for the call — trying to push that hope out of his mind is a way to cope with an uncertain wait, not a sign he stopped caring.'},
      {context:`"It was all up to the team staff. There was not anything he could do but be on hold."`, prompt:'What does this tell you about Dell\'s control over the situation?', 
        options:['He had full control of the decision','He had no control and just had to wait','He could still change the staff\'s minds','He had already made the team'], answer:1,
        explain:'"All up to the team staff" and "nothing he could do" both point to the same thing — the decision was entirely out of Dell\'s hands.'},
      {context:`"Dell had to lift his phone quick when it rang to check if it was a prank."`, prompt:'Why would Dell think the call might be a prank?', 
        options:['He gets prank calls every day','The moment felt important enough that he wanted to make sure it was real','He didn\'t want to answer the phone','He was expecting a call from a friend'], answer:1,
        explain:'Checking whether big news is "a prank" is something people do when a moment feels too important or unbelievable to trust right away.'},
      {context:`"It was not! The call was not just from anyone."`, prompt:'What does the repeated "not" emphasize here?', 
        options:['That the call was unimportant','That this call was different and significant','That Dell hung up','That the call was from a stranger'], answer:1,
        explain:'The double emphasis — "it was not" a prank, and "not just from anyone" — builds up how significant and real this particular call was.'},
      {context:`"They did pick him and only him."`, prompt:'What does "and only him" emphasize?', 
        options:['That the team picked several players','That Dell was the single, exact choice for the one spot','That Dell picked the team','That someone else was picked instead'], answer:1,
        explain:'Earlier the story says there was "one spot on the team" — "only him" confirms Dell was the single specific player chosen for that one spot.'},
      {context:`"Dell had to grasp the news fast."`, prompt:'What does this suggest about how Dell was feeling?', 
        options:['He was calm and unaffected','He needed a moment to process something big and sudden','He didn\'t understand the news','He was falling asleep'], answer:1,
        explain:'Having to "grasp" news quickly suggests it was a lot to take in all at once — a natural reaction to unexpectedly huge news.'},
      {context:'Think about the whole story.', prompt:'What is one theme this story explores?', 
        options:['Hard work can pay off, but the outcome is still out of your hands until it\'s decided','Try outs never matter','Waiting is easy when you want something badly','Teams always pick the top-ranked player'], answer:0,
        explain:'Dell earns the top ranking through his skill, but the story spends just as much time on the powerless waiting before the decision — showing that effort matters, but the outcome is still someone else\'s call.'},
    ]},
  { id:'vocab', tab:'Vocab', title:"Case File 3 — Vocabulary Clues", icon:'🔍',
    intro:"Every good detective reads for clues hidden in context. Figure out what each word means the way Dell used it in the story.",
    type:'mc', points:10,
    questions:[
      {context:`"Dell had been put at the top of the ranks at the try out."`, prompt:'What does ranks mean here?', 
        options:['A row of seats','A list ordering players by how well they performed','A type of uniform','A group of coaches'], answer:1,
        explain:'"Top of the ranks" describes Dell\'s position on a list that orders players by performance — being at the top means he performed best.'},
      {context:`"His runs were swift and his jumps were long."`, prompt:'What does swift mean here?', 
        options:['Slow and careful','Fast','Quiet','Clumsy'], answer:1,
        explain:'Swift describes speed — paired with "long" jumps, it\'s listing Dell\'s athletic strengths, so it must mean fast, not slow.'},
      {context:`"There was not anyone who could crush his stats."`, prompt:'What does crush mean here?', 
        options:['Physically break something','Beat by a wide margin','Politely ask','Copy exactly'], answer:1,
        explain:'"Crush his stats" is a way of saying beat his numbers decisively — no one could out-perform Dell\'s results.'},
      {context:`"The team staff said that they did want a jock with his skills."`, prompt:'What does jock mean here?', 
        options:['A piece of equipment','An athlete','A type of shoe','A coach'], answer:1,
        explain:'The sentence is about wanting someone "with his skills" for the team — jock here refers to a skilled athlete, which is what Dell is.'},
      {context:`"Dell had big wishes that he would get the call."`, prompt:'What does wishes mean here?', 
        options:['Complaints','Hopes for something he wants','Instructions','Memories'], answer:1,
        explain:'"Big wishes" paired with wanting "the call" shows Dell hoping for a specific outcome — that\'s what wishes means in this context.'},
      {context:`"There was not anything he could do but be on hold."`, prompt:'What does on hold mean here?', 
        options:['Answering the phone','Waiting without being able to act','Winning the spot','Talking to the coach'], answer:1,
        explain:'"Nothing he could do but" signals Dell is stuck waiting — "on hold" here means waiting in uncertainty, not literally holding a phone call.'},
      {context:`"Dell had to lift his phone quick when it rang."`, prompt:'What does lift mean here?', 
        options:['Exercise with weights','Pick something up','Raise his voice','Push something down'], answer:1,
        explain:'"Lift his phone" describes picking the phone up to answer it — a simple physical action, not weightlifting.'},
      {context:`"He had to check if it was a prank."`, prompt:'What does prank mean here?', 
        options:['An important call','A trick or joke played on someone','A wrong number','A voicemail'], answer:1,
        explain:'Checking if a call is "a prank" means checking if it\'s a trick rather than genuine news — that uncertainty is why Dell double-checks.'},
      {context:`"Dell had to grasp the news fast."`, prompt:'What does grasp mean here?', 
        options:['Physically hold onto something','Understand something quickly','Write something down','Ignore something'], answer:1,
        explain:'"Grasp the news" means mentally taking in and understanding the news, not physically holding an object.'},
      {context:`"Then he ran off to tell his mom, dad, and all his pals."`, prompt:'What does pals mean here?', 
        options:['Teachers','Strangers','Friends','Teammates only'], answer:2,
        explain:'Pals is an informal word for friends — listed alongside his mom and dad as people Dell wants to share his good news with.'},
    ]},
  { id:'spelling', tab:'Spelling', title:"Case File 4 — Spelling Forensics", icon:'✏️',
    intro:"A detective's notes have to be exact. Listen to each word and spell it correctly to file it as evidence.",
    type:'spell', points:15,
    questions:[
      {word:'draft', sentence:'The big draft was coming fast.'},
      {word:'swift', sentence:'His runs were swift.'},
      {word:'crush', sentence:'No one could crush his stats.'},
      {word:'staff', sentence:'The team staff made the pick.'},
      {word:'class', sentence:'Dell was in the class of picks.'},
      {word:'spot', sentence:'There was one spot on the team.'},
      {word:'grasp', sentence:'Dell had to grasp the news fast.'},
      {word:'rang', sentence:'The phone rang and Dell answered.'},
      {word:'prank', sentence:'He checked if it was a prank.'},
      {word:'mind', sentence:'He put it out of his mind.'},
      {word:'hold', sentence:'Dell had to be on hold.'},
      {word:'skills', sentence:'The staff wanted a jock with his skills.'},
    ]},
  { id:'structure', tab:'Structure', title:"Case File 5 — Structure Analysis", icon:'🧩',
    intro:"Every word is a piece of evidence with structure. Mark the blends, digraphs, and sounds to crack the code.",
    type:'mc', points:10,
    questions:[
      {context:'draft', prompt:'Which letters form the beginning consonant blend?', options:['dr','af','ft','ra'], answer:0,
        explain:'/d/ and /r/ stay separately heard, blended together at the start of draft — that makes dr the blend.'},
      {context:'draft', prompt:'Which letters form the ending blend?', options:['dr','af','ft','ra'], answer:2,
        explain:'/f/ and /t/ are both still heard at the end of draft, blended together — that makes ft an ending blend.'},
      {context:'swift', prompt:'Which letters form the beginning blend?', options:['sw','if','ft','wi'], answer:0,
        explain:'/s/ and /w/ blend together at the start of swift while both sounds stay separate — that\'s the definition of a blend.'},
      {context:'crush', prompt:'Which letters form the beginning blend?', options:['cr','us','sh','ru'], answer:0,
        explain:'/c/ and /r/ blend together at the start of crush, with both sounds still heard.'},
      {context:'crush', prompt:'Which letters form the ending digraph?', options:['cr','us','sh','ru'], answer:2,
        explain:'S and h together make one brand new sound, /sh/, instead of two separate sounds — that\'s what makes sh a digraph.'},
      {context:'grasp', prompt:'How many consonant blends does this word have?', options:['0','1','2','3'], answer:2,
        explain:'Grasp has a blend at the start (gr) and another at the end (sp) — two separate blends in one word.'},
      {context:'rang', prompt:'Which letters form the welded ending?', options:['r','an','ang','ng'], answer:2,
        explain:'"Ang" is a welded sound — the a, n, and g glue together into one chunk that is always read as a unit.'},
      {context:'prank', prompt:'Which letters form the welded ending?', options:['pr','an','ank','nk'], answer:2,
        explain:'"Ank" is a welded sound, taught alongside ang, ink, onk, and unk — the vowel and consonants after it are chunked together as one unit.'},
      {context:'mind', prompt:'Which letters form the welded ending?', options:['m','in','ind','nd'], answer:2,
        explain:'"Ind" is a welded sound, taught alongside ild, old, olt, and ost — always chunked as one unit rather than split into separate letters.'},
      {context:'hold', prompt:'Which letters form the welded ending?', options:['h','ol','old','ld'], answer:2,
        explain:'"Old" is a welded sound — the o, l, and d glue together into one chunk, the same way ild, ind, olt, and ost do.'},
    ]},
];

STORY_PACKS['the_draft'] = {
  id: 'the_draft',
  title: "The Draft",
  substep: '2.4B',
  blurb: "Waiting for the call that could change everything — closed syllables, blends, and welded sounds.",
  type: 'controlled', // 'controlled' (WRS-decodable) or 'authentic' (real-world text)
  keyTerms: KEY_TERMS_THE_DRAFT,
  paragraphs: STORY_PARAGRAPHS_THE_DRAFT,
  rounds: ROUNDS_THE_DRAFT,
};
STORY_ORDER.push('the_draft');
